"""粒子贴图：叶、花瓣、火星、雨丝、雪片、尘埃、萤火、火花、破势碎片。

叶与花瓣、碎片是手画的灰度像素模板（运行时乘色：叶乘绿/枯黄、花瓣乘粉、碎片乘玉青或金）；
发光类（火星、萤火、火花、雪、尘）按像素中心的解析式算 alpha。
火星是少数带颜色的一种——火本来就不需要运行时再染。
"""

from __future__ import annotations

import math

from PIL import Image

import palette as P
from fx_textures import _q, smoothstep
from sprites_core import tpl

# 灰度码：# 亮面 / o 中间 / + 暗面 / - 最暗的边
GREY = {"#": 255, "o": 214, "+": 160, "-": 112}


def grey_tpl(text: str, w: int, h: int) -> Image.Image:
    rows = tpl(text)
    img = Image.new("RGBA", (w, h), (255, 255, 255, 0))
    px = img.load()
    for j, r in enumerate(rows[:h]):
        for i, ch in enumerate(r[:w]):
            if ch in GREY:
                v = GREY[ch]
                px[i, j] = (v, v, v, 255)
    return img


def strip(frames: list[Image.Image]) -> Image.Image:
    w, h = frames[0].width, frames[0].height
    out = Image.new("RGBA", (w * len(frames), h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        out.paste(f, (i * w, 0))
    return out


LEAVES = [
    """
    ......##
    ....#o##
    ...#oo+.
    ..#oo+..
    .#oo+...
    .oo+....
    .++.....
    +.......
    """,
    """
    ........
    ..####..
    .#oooo#.
    #ooo+++o
    .+++++o.
    ..++++..
    ........
    ........
    """,
    """
    ....#...
    ...#o#..
    ..#oo+..
    ..#o+...
    ..#o+...
    ..o++...
    ...+....
    ...-....
    """,
    """
    ........
    ........
    .##.....
    #oo#....
    .ooo#...
    ..+oo#..
    ...++-..
    ........
    """,
]
PETALS = [
    """
    ........
    ...##...
    ..#oo#..
    ..#oo+..
    ...o+...
    ........
    ........
    ........
    """,
    """
    ........
    ..##....
    .#oo#...
    ..ooo+..
    ...++...
    ........
    ........
    ........
    """,
    """
    ........
    ........
    ..###o..
    .oooo+..
    ........
    ........
    ........
    ........
    """,
    """
    ........
    ..#.#...
    .#o#o#..
    .ooooo..
    ..+o+...
    ...+....
    ........
    ........
    """,
]
SHARDS = [
    """
    ............
    .....#......
    ....#o#.....
    ...#ooo+....
    ..#ooo+++...
    .#ooo+++++..
    ..o+++++-...
    ...+++--....
    ....+--.....
    .....-......
    ............
    ............
    """,
    """
    .........##.
    ........#o+.
    .......#o+..
    ......#o+...
    .....#o+....
    ....#o+.....
    ...#o+......
    ..#o+.......
    .oo+........
    .+-.........
    ............
    ............
    """,
    """
    ............
    ..#.........
    ..#o#.......
    ..#oo#......
    ..#ooo#.....
    ..#oooo#....
    ..#oo+++#...
    ..#o+++++-..
    ..--------..
    ............
    ............
    ............
    """,
    """
    ............
    ......#.....
    .....#o#....
    ....#ooo+...
    ...#oooo++..
    ....oooo+...
    .....o++....
    ......+.....
    ......-.....
    ............
    ............
    ............
    """,
    """
    ............
    ............
    ............
    .....#......
    ....#o#.....
    ...#oo+#....
    ....o++.....
    .....-......
    ............
    ............
    ............
    ............
    """,
    """
    ............
    ............
    ...####.....
    ..#oooo#....
    ..#ooo+++#..
    ...oo++++-..
    ....+++--...
    .....--.....
    ............
    ............
    ............
    ............
    """,
]


def leaves() -> Image.Image:
    return strip([grey_tpl(t, 8, 8) for t in LEAVES])


def petals() -> Image.Image:
    return strip([grey_tpl(t, 8, 8) for t in PETALS])


def shards() -> Image.Image:
    return strip([grey_tpl(t, 12, 12) for t in SHARDS])


def _dot(size: int, r_core: float, r_halo: float, core_a: float = 255.0, halo_a: float = 150.0,
         color=(255, 255, 255)) -> Image.Image:
    img = Image.new("RGBA", (size, size), color + (0,))
    px = img.load()
    c = size / 2.0
    for y in range(size):
        for x in range(size):
            d = math.hypot(x + 0.5 - c, y + 0.5 - c)
            if d <= r_core:
                a = core_a
            else:
                a = halo_a * (1.0 - smoothstep(r_core, r_halo, d))
            px[x, y] = color + (_q(a),)
    return img


def embers() -> Image.Image:
    """火星：芯子黄白、外圈橙红，四帧明灭。带颜色。"""
    core = P.mix("gold4", "paper", 0.3)
    mid = P.c("gold3")
    edge = P.c("red3")
    frames = []
    for rc, rh in ((1.0, 2.6), (1.5, 3.4), (1.2, 3.0), (0.7, 2.2)):
        img = Image.new("RGBA", (8, 8), (0, 0, 0, 0))
        px = img.load()
        for y in range(8):
            for x in range(8):
                d = math.hypot(x + 0.5 - 4.0, y + 0.5 - 4.0)
                if d <= rc:
                    px[x, y] = core + (255,)
                elif d <= rc + 0.9:
                    px[x, y] = mid + (230,)
                elif d <= rh:
                    t = (d - rc - 0.9) / max(0.01, rh - rc - 0.9)
                    px[x, y] = edge + (_q(170 * (1.0 - t)),)
        frames.append(img)
    return strip(frames)


def rain() -> Image.Image:
    """雨丝：4×16，中间两列从上到下由淡到浓。运行时斜着落。"""
    def a(x: float, y: float) -> float:
        across = 1.0 if 1.0 <= x <= 3.0 else 0.0
        return 190.0 * across * smoothstep(0.0, 1.0, y / 16.0) * (0.55 if x < 2.0 else 1.0)

    img = Image.new("RGBA", (4, 16), (255, 255, 255, 0))
    px = img.load()
    for y in range(16):
        for x in range(4):
            px[x, y] = (255, 255, 255, _q(a(x + 0.5, y + 0.5)))
    return img


def snow() -> Image.Image:
    return strip([_dot(8, 0.8, 1.8, 255, 170), _dot(8, 1.3, 2.6, 255, 150), _dot(8, 1.8, 3.6, 240, 120)])


def dust() -> Image.Image:
    return _dot(4, 0.6, 2.0, 210, 150)


def firefly() -> Image.Image:
    return strip([_dot(8, 1.0, 3.8, 255, 140), _dot(8, 0.6, 2.8, 200, 90)])


def spark() -> Image.Image:
    """火花：四角星，三帧由长到短。"""
    frames = []
    for ray in (3.6, 2.6, 1.4):
        img = Image.new("RGBA", (8, 8), (255, 255, 255, 0))
        px = img.load()
        for y in range(8):
            for x in range(8):
                dx, dy = abs(x + 0.5 - 4.0), abs(y + 0.5 - 4.0)
                a = 0.0
                if dx < 0.6:
                    a = max(a, 255.0 * (1.0 - smoothstep(0.0, ray, dy)))
                if dy < 0.6:
                    a = max(a, 255.0 * (1.0 - smoothstep(0.0, ray, dx)))
                if dx < 1.1 and dy < 1.1:
                    a = max(a, 200.0)
                px[x, y] = (255, 255, 255, _q(a))
        frames.append(img)
    return strip(frames)
