"""非人形 / 特殊敌人的战斗精灵。

敌人站在画面左侧、面朝右边的我方，所以这里的图一律**面朝右**（人形敌人用人物表，
运行时水平翻转；这里的兽与光球不翻）。

每张表一行：待机×2、出招、受击、倒下（光球是 脉动×4、受击、消散）。
待机第二帧、受击帧由第一帧推出来（整体下沉一格 / 往后一缩再闭眼），
出招与倒下各画一张——这两帧的剪影与站姿差得太远，推不出来。

逐一核对 b03–b05 的战斗单位（data/roles 的 name/note）：
  wild_wolf 恶狼            兽：灰狼，压低前身、龇牙
  long_zhong_shou 笼中兽    兽：关久了的活物，怕光见人就扑——瘦、秃斑、惨白的眼
  jiang_shou 僵兽           「走得很慢，两只脚上的分量一样重」：直立佝偻的死物，炼尸炼到一半
  mofu_shigui 墨府尸傀      修仙者斗法留下的遗物：高大的人形死物，残破长袍、锁链、醒过来的眼
  mo_juren_yuanshen 墨居仁元神、yu_zitong 余子童（元神）、hanli_yuanshen 韩立元神：
                            识海之战里的光球；余子童「比韩立大了有一圈有余」→ 40 见方
  hei_xiong 黑熊是人（铁拳会头目），走人物表；qu_hun 曲魂是巨汉，同样走人物表（24×32）。
  ye_zhu 野猪（野外遭遇 be03–be05，改编）：敦实、鬃毛、獠牙，出招是低头一撞。
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from PIL import Image

import palette as P
from sprites_core import Canvas, Materials, add_outline, cloth_ramp, grid_sheet, to_image, tpl


@dataclass(frozen=True)
class Beast:
    id: str
    name: str
    w: int
    h: int
    idle: tuple[str, ...]
    attack: tuple[str, ...]
    down: tuple[str, ...]
    ramps: dict[str, list[tuple[int, int, int]]]
    codes: dict[str, tuple[str, int]]
    leg_top: int          # 待机呼吸时，这一行以上整体下沉
    note: str = ""


def _codes(extra: dict[str, tuple[str, int]] | None = None) -> dict[str, tuple[str, int]]:
    base = {
        "A": ("fur", 3), "B": ("fur", 2), "C": ("fur", 1), "D": ("fur", 0),
        "E": ("belly", 3), "F": ("belly", 2), "G": ("belly", 1),
        "e": ("eyeglow", 3), "n": ("ink", 1), "W": ("tooth", 3), "r": ("mouth", 2),
        "k": ("claw", 2),
    }
    if extra:
        base.update(extra)
    return base


# ===========================================================================
# 恶狼
# ===========================================================================

WOLF_IDLE = tpl("""
................................
................................
......................A..A......
.....................AB.AB......
....................ABBBBBBB....
.............D.D.D.ABBBBBeBBB...
...........DDADADADBBBBBBBBBBBn.
........AAABBBBBBBBBBBBBBCWWWW..
......AABBBBBBBBBBBBBBBBCrrrr...
.....ABBBBBBBBBBBBBBBBBCWWWW....
....ABBBBBBBBBBBBBBBBBCCCCC.....
...AB.BBBBFFFFFFFFBBBBC.........
..AB..CBBBGGGGGGGGBBBC..........
..B...CBBC.......CBBC...........
......CBBC.......CBBDC..........
.....CBC.DC......CBC.DC.........
.....CBC.DC......CBC.DC.........
.....CB..DC......CBC.DC.........
......CB.DC......CBC..DC........
......CB.DC......CBC..DC........
......CB.DC......CBC..DC........
......kkkDkk.....kkk..Dkk.......
................................
................................
""")
WOLF_ATTACK = tpl("""
................................
................................
................................
........................A..A....
.......................AB.AB....
..............D.D.D...ABBBBBB...
............DDADADADABBBBBeBBB..
....AAAAAAABBBBBBBBBBBBBBBBBBBBn
..AABBBBBBBBBBBBBBBBBBBBBBBCWWWW
.ABBBBBBBBBBBBBBBBBBBBBBBBCrrrr.
AB.CBBBBFFFFFFFFFBBBBBBBBCrrr...
B..CCBBBGGGGGGGGGGBBBBBBCWWWW...
....CCBBBC.......CBBBBBC........
...CBBC.DC........CBBBBC........
..CBC...DC.........CBBDBC.......
.CBC.....DC.........CBC.DC......
CBC.......DC.........CBC.DC.....
kk........Dkk.........kkk.Dkk...
................................
................................
................................
................................
................................
................................
""")
WOLF_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
....................A..A........
..............DDDD.AB.ABB.......
......AAAAAAAABBBBBBBBBBBBB.....
...AABBBBBBBBBBBBBBBBBBBBBBBBn..
..ABBBBFFFFFFFFFBBBBBBBCCCCCC...
.ABCCCCGGGGGGGGGCCBBBBCC........
.B..CDCDC...CDCDC..DCC..........
........................kk......
................................
................................
""")

WOLF = Beast(
    id="wild_wolf", name="恶狼", w=32, h=24,
    idle=tuple(WOLF_IDLE), attack=tuple(WOLF_ATTACK), down=tuple(WOLF_DOWN),
    ramps={
        # 深灰狼：背上一道更暗的鬃（D），眼是两格亮金——在暗的战斗背景上先看见的就是那双眼
        "fur": [P.c("ink1"), P.mix("stone0", "ink3", 0.3), P.mix("stone1", "stone2", 0.3), P.c("stone3")],
        "belly": [P.c("stone2"), P.c("stone3"), P.c("stone4"), P.c("stone5")],
        "eyeglow": [P.c("gold1"), P.c("gold2"), P.c("gold3"), P.mix("gold4", "paper", 0.3)],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red2"), P.c("red2")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
    },
    codes=_codes(), leg_top=14,
    note="教学关的普通野兽：灰狼，抬头竖耳、张嘴龇牙、颈背鬃毛竖起、收腹长腿。",
)

# ===========================================================================
# 笼中兽：同是四足，但瘦、弓背、秃斑、惨白的眼——关久了怕光
# ===========================================================================

CAGE_IDLE = tpl("""
................................
................................
................................
................................
................................
...........AAAAAA...............
.........AABBBBBBAA.............
.......AABBBSSBBBBBAA.....A.A...
......ABBBBSSSBBBBBBBA...AB.AB..
.....ABBBBBBSBBBBBBBBBAAABBBBB..
....ABBBABABABABBBBBBBBBBBBBeeB.
...AB.CBBABABABABBBBBBBBBBBBBBB.
..AB..CBBBBBBBBBBBBBBBBBBBBBBBBn
..B...CBBGGGGGGGBBBCBBBBBBCrWrW.
......CBBC.......CBBC..CCCWrWr..
......CBC.DC.....CBC.DC.........
.....CBC..DC.....CBC.DC.........
.....CB...DC.....CB..DC.........
.....CB...DC.....CB..DC.........
....CB....DC....CB...DC.........
....kk...Dkk....kk..Dkk.........
................................
................................
................................
""")
CAGE_ATTACK = tpl("""
................................
................................
................................
................................
............AAAAAA..............
..........AABBBBBBAA.......A.A..
........AABBBSSBBBBBAA....AB.AB.
.......ABBBBSSSBBBBBBBAAAABBBBB.
.....AABBBBBBSBBBBBBBBBBBBBBeeB.
...AABBBABABABABBBBBBBBBBBBBBBBn
..AB.CBBABABABABBBBBBBBBBBCrWrW.
.AB..CBBBBBBBBBBBBBBBBBBCCrrrr..
.B...CCBGGGGGGGBBBBBBBBCCWrWr...
.....CBBC........CBBBBCC........
....CBC.DC........CBBDBC........
...CBC...DC........CBC.DC.......
..CBC.....DC........CBC.DC......
.CBC.......DC........CBC.DC.....
.kk........Dkk.......kkk.Dkk....
................................
................................
................................
................................
................................
""")
CAGE_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........AAAAAAAA.............
........AAABBBSBBBBAAA..........
......AABBBBSSSBBBBBBBBA........
....AABBBBBBBSBBBBBBBBBBBA......
...ABBBBGGGGGGGGBBBBBBBCBBBn....
..ABCCCCGGGGGGGGCCBBBBCCCCC.....
..BC.DCDC...DCDC..DCCC..........
.......................kk.......
................................
................................
................................
""")

CAGE = Beast(
    id="long_zhong_shou", name="笼中兽", w=32, h=24,
    idle=tuple(CAGE_IDLE), attack=tuple(CAGE_ATTACK), down=tuple(CAGE_DOWN),
    ramps={
        # 弓着的背上一排肋骨（受光色画的横纹）要看得见，所以受光面比恶狼拉得更开
        "fur": [P.c("ink1"), P.mix("stone0", "violet0", 0.3), P.mix("stone1", "violet1", 0.2), P.mix("stone3", "violet2", 0.15)],
        "belly": [P.mix("skin0", "stone1", 0.5), P.mix("skin1", "stone2", 0.5), P.mix("skin1", "stone3", 0.4), P.mix("skin2", "stone4", 0.4)],
        "patch": [P.mix("skin0", "stone1", 0.4), P.mix("skin1", "stone2", 0.45), P.mix("skin2", "stone3", 0.45), P.mix("skin2", "stone4", 0.3)],
        "eyeglow": [P.c("gold2"), P.c("gold3"), P.mix("gold4", "paper", 0.5), P.c("paper")],
        "tooth": [P.c("stone4"), P.c("stone5"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red0"), P.c("red1"), P.c("red1")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
    },
    codes=_codes({"S": ("patch", 2)}), leg_top=14,
    note="暗道笼子里关久了的活物（怕光、见人就扑）：背弓得老高、头垂得比肩低、一排肋骨、秃斑、惨白的眼。与恶狼同为四足，剪影是饿坏了的那一种。",
)

# ===========================================================================
# 僵兽：直立佝偻，两条长臂垂着，一身死人皮色，缠着烂布条
# ===========================================================================

STIFF_IDLE = tpl("""
................................
................................
................................
................................
................................
................................
..........AAAA..................
........AABBBBAA................
.......ABBBBBBBBA...............
......ABBBBBBBBBBAAA............
......ABBBBBBBBBBBBBAA..........
.....ABBBBBBBBBBBBBBBBAAA.......
.....ABBBBBBBBBBBBBBBBBBBA......
.....CBBBBBBBBBBBBBBBBBeBBB.....
.....CBBBBBBBBBBBBBBBBBBBBBC....
.....CBBBBBBBBBBCBBBBBBBnWWC....
......CBBBBBBBBC.CBBBBBCCC......
......CBBBBBBBC...CBBBC.........
.......CBBBBBC.....CBBC.........
.......TTTTTTT.....CBTC.........
.......CBBBBBC.....CBTC.........
......CBBBCBBBC....CBBC.........
......CBBC.CBBC....CBBBC........
.....CBBC...CBBC...kCkCk........
.....CBC.....CBC................
.....CBC.....CBBC...............
....CBBC......CBC...............
....kkk.......kkk...............
................................
................................
................................
................................
""")
STIFF_ATTACK = tpl("""
................................
................................
................................
................................
................................
................................
................................
..........AAAA..................
........AABBBBAA................
.......ABBBBBBBBA...............
......ABBBBBBBBBBAAAA...........
......ABBBBBBBBBBBBBBAAAA.......
.....ABBBBBBBBBBBBBBBBBBBA......
.....CBBBBBBBBBBBBBBBBBBeBBB....
.....CBBBBBBBBBBBBBBBBBBBBBBC...
.....CBBBBBBBBBBBBAAAAAAnWWWCk..
......CBBBBBBBBCBBBBBBBBBBBTTkk.
......CBBBBBBBCCCCCCCCCCCCCCk...
.......CBBBBBC..................
.......TTTTTTT..................
.......CBBBBBC..................
......CBBBCBBBC.................
.....CBBC...CBBC................
....CBBC.....CBBC...............
...CBBC.......CBC...............
...CBC........CBBC..............
..CBBC.........CBC..............
..kkk..........kkk..............
................................
................................
................................
................................
""")
STIFF_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............AAAAAA............
..........AAAABBBBBBAA..........
.......AAABBBBBBBBBBBBA.........
.....AABBBBBTTBBBBBBBBBBA.......
....ABBBBBBBTTBBBBBBBBBBBBAA....
...ABBBBBBBBBBBBBBBBBBBBBBBBn...
..kBCCCCCCCCBBBBBBBBBCCCCCCC....
..kk.CBC..CBBCCCCCCCCCkCk.......
.....kkk..kkk...................
................................
""")

STIFF = Beast(
    id="jiang_shou", name="僵兽", w=32, h=32,
    idle=tuple(STIFF_IDLE), attack=tuple(STIFF_ATTACK), down=tuple(STIFF_DOWN),
    ramps={
        "fur": cloth_ramp(P.mix("stone2", "jade1", 0.35)),
        "wrap": [P.c("stone1"), P.c("stone2"), P.c("stone3"), P.c("stone4")],
        "eyeglow": [P.c("jade2"), P.c("jade3"), P.c("jade4"), P.c("paper")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
        "belly": cloth_ramp(P.c("stone3")),
        "tooth": [P.c("stone4"), P.c("stone5"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red0"), P.c("red1"), P.c("red1")],
    },
    codes=_codes({"T": ("wrap", 2)}), leg_top=23,
    note="墨大夫炼尸术试到一半的活物：直立、佝偻、长臂垂爪、青灰死人皮、身上缠着烂布条；眼里一点幽绿。",
)

# ===========================================================================
# 墨府尸傀：高大人形，残破长袍，腕上断锁链，眼里醒过来的一点光
# ===========================================================================

SHIGUI_IDLE = tpl("""
................................
................................
................................
................................
............SSSS................
...........SSSSSS...............
..........SSSSSSSS..............
..........SkeSSekS..............
..........SSSSSSSs..............
...........sSSSSs...............
.........AABBTTBBAA.............
.......AABBBBTTBBBBAA...........
......ABBBBBBTTBBBBBBA..........
......ABBBBBBTTBBBBBBC..........
......ABBBBBBBTBBBBBBC..........
......ABBCBBBBBBBBCBBC..........
.....ABBCCBBBBBBBBCCBBC.........
.....ABBC.BBBBBBBBC.BBC.........
.....ABC..YYYYYYYYC..BC.........
.....SSs..BBBBBBBBC..Ss.........
.....SsZ..BBBBBBBBC..sZ.........
......ZZ..BBBBCBBBC..ZZ.........
.......Z..BBBBCBBBBC..Z.........
.......Z..BBBBCBBBBC..Z.........
.........ABBBBCBBBBC............
.........ABBBBCCBBBBC...........
.........ABBBC.CBBBBC...........
.........ABBB..CBBBBC...........
.........ABBC...CBBBC...........
........ABBC....CBBBBC..........
........ABBC.....CBBBC..........
........BBCC.....CCBBC..........
........B.C.......C.B...........
.........ss.......ss............
........ssk.......ssk...........
................................
................................
................................
................................
................................
""")
SHIGUI_ATTACK = tpl("""
................................
................................
................................
................................
................................
................................
.............SSSS...............
............SSSSSS..............
...........SSSSSSSS.............
...........SkeSSekS.............
...........SSSSSSSs.............
............sSSSSs..............
..........AABBTTBBAAAA..........
........AABBBBTTBBBBBBAAAAAASs..
.......ABBBBBBTTBBBBBBBBBBBBSsZ.
.......ABBBBBBTTBBBBBBBBBCCC..ZZ
.......ABBBBBBBTBBBBBBC.......Z.
......ABBCBBBBBBBBCBBC..........
......ABBCCBBBBBBBBCCBC.........
......ABBC.BBBBBBBBC.BC.........
......ABC..YYYYYYYYC.BC.........
......SSs..BBBBBBBBC.Ss.........
......SsZ..BBBBBBBBC.sZ.........
.......ZZ..BBBBCBBBC.ZZ.........
........Z..BBBBCBBBBC.Z.........
..........ABBBBCBBBBC...........
.........ABBBBC.CBBBBC..........
........ABBBBC...CBBBBC.........
.......ABBBC......CBBBBC........
......ABBBC........CBBBC........
......BBCC..........CCBBC.......
......B.C............C.B........
......ss..............ss........
.....ssk..............ssk.......
................................
................................
................................
................................
................................
................................
""")
SHIGUI_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............SSSS................
..........AASSSSSSAA............
........AABBSkSSekBBAA..........
.......ABBBBSSSSSSBBBBBA........
......ABBBBBBTTBBBBBBBBBBA......
.....ABBBBBBBBTTBBBBBBBBBBBA....
....ABBYYYYYYYYYYBBBBBBBBBBBBA..
...SsBBBBBBBBBBBBBBBBBCCCCCCCC..
..ZZsCCCCCCCCCCCCCCCCCCC..ss....
..Z....................ssk......
................................
................................
................................
................................
""")

SHIGUI = Beast(
    id="mofu_shigui", name="墨府尸傀", w=32, h=40,
    idle=tuple(SHIGUI_IDLE), attack=tuple(SHIGUI_ATTACK), down=tuple(SHIGUI_DOWN),
    ramps={
        "fur": cloth_ramp(P.mix("ink3", "violet0", 0.35)),      # 残破的深色长袍
        "trimrag": cloth_ramp(P.mix("stone2", "gold0", 0.2)),
        "corpse": cloth_ramp(P.mix("stone3", "jade1", 0.35)),
        "eyeglow": [P.c("red2"), P.c("red3"), P.c("red4"), P.c("gold4")],
        "chain": [P.c("ink2"), P.c("ink3"), P.c("ink5"), P.c("ink6")],
        "belt": cloth_ramp(P.mix("wood1", "ink2", 0.4)),
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
        "belly": cloth_ramp(P.c("stone3")),
        "tooth": [P.c("stone4"), P.c("stone5"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red0"), P.c("red1"), P.c("red1")],
    },
    codes=_codes({
        "S": ("corpse", 2), "s": ("corpse", 1), "T": ("trimrag", 2), "Y": ("belt", 2),
        "Z": ("chain", 2), "k": ("corpse", 0),
    }),
    leg_top=24,
    note="修仙者斗法留下的遗物、封在马厩地窖里：比人高、残破深色长袍、死人皮、腕上断链、醒过来的一对红眼。",
)

# ===========================================================================
# 野猪：前重后轻的楔形身子、肩上一溜鬃毛、脸颊一道暗线把头分出来、长嘴拱鼻、上翘的白獠牙
# ===========================================================================

BOAR_IDLE = tpl("""
................................
................................
................................
................................
................................
...........D.D.D.D..............
.........DDADADADADA............
.......AABBBBBBBBBBBBA...A......
.....AABBBBBBBBBBBBBBBAAABA.....
....ABBBBBBBBBBBBBBBBBBBBBBA....
...ABBBBBBBBBBBBBBBBBBCBBBBBA...
..AB.BBBBBBBBBBBBBBBBBCBBeBBBA..
..B..CBBBBBBBBBBBBBBBBBCBBBBWBn.
.....CBBBBBBBBBBBBBBBBBBCBBBWnnn
.....CBBBBBBBBBBBBBBBBBBBCCCCC..
.....CCBBBFFFFFFFFFBBBBBC.......
......CCGGGGGGGGGGGGCBCC........
......DCBC.DCBC....DCBC.DCBC....
......DCBC.DCBC....DCBC.DCBC....
......DCB..DCB.....DCB..DCB.....
......Dkk..Dkk.....Dkk..Dkk.....
................................
................................
................................
""")
BOAR_ATTACK = tpl("""
................................
................................
................................
................................
................................
................................
..........D.D.D.D...............
........DDADADADADA.............
......AABBBBBBBBBBBBA...........
....AABBBBBBBBBBBBBBBAA..A......
..AABBBBBBBBBBBBBBBBBBBAABA.....
.ABBBBBBBBBBBBBBBBBBBBBBCBBBA...
.B..CBBBBBBBBBBBBBBBBBBBCBeBBBA.
....CBBBBBBBBBBBBBBBBBBBBCBBBWBn
....CBBBBBBBBBBBBBBBBBBBBBCBBWnn
....CCBBFFFFFFFFFFBBBBBBBBCCCCC.
.....CCGGGGGGGGGGGGGCBBCC.......
...DCBC.......DCBC...DCBC.DCBC..
..DCBC.........DCBC...DCBC.DCBC.
.DCB............DCB....DCB..DCB.
Dkk..............Dkk....Dkk..Dkk
................................
................................
................................
""")
BOAR_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............D.D.D...............
..........DDADADADA...A.........
.......AABBBBBBBBBBBAAABA.......
....AABBBBBBBBBBBBBBBBBBBCBA....
...ABBBBBFFFFFFFFFBBBBBBBCBBWBn.
..ABCCCGGGGGGGGGGGCCBBBBBCBBWnn.
..BC.DCBC.DCBC..DCBC.DCBCCCCCC..
................................
................................
................................
................................
""")

BOAR = Beast(
    id="ye_zhu", name="野猪", w=32, h=24,
    idle=tuple(BOAR_IDLE), attack=tuple(BOAR_ATTACK), down=tuple(BOAR_DOWN),
    ramps={
        "fur": [P.c("ink1"), P.mix("wood0", "ink2", 0.35), P.mix("wood1", "stone1", 0.45), P.mix("wood2", "stone2", 0.45)],
        "belly": [P.mix("wood1", "stone1", 0.5), P.mix("wood2", "stone2", 0.5), P.mix("wood3", "stone3", 0.5), P.mix("wood4", "stone4", 0.5)],
        "eyeglow": [P.c("red1"), P.c("red2"), P.c("red3"), P.c("red4")],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red1"), P.c("red2")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.mix("skin0", "ink2", 0.5), P.c("ink3")],
    },
    codes=_codes(), leg_top=17,
    note="野外遭遇的山林野兽（改编）：敦实、肩上鬃毛竖起、白獠牙上翘；出招是低头一撞（role note）。",
)

BEASTS = (WOLF, CAGE, STIFF, SHIGUI, BOAR)


def _canvas_from(rows: tuple[str, ...], beast: Beast) -> Canvas:
    c = Canvas(beast.w, beast.h)
    c.stamp(list(rows), 0, 0, beast.codes)
    return c


def _breath(c: Canvas, leg_top: int) -> Canvas:
    """待机第二帧：腿以上整体下沉一格（腿不动，身子压一压）。"""
    out = c.copy()
    for y in range(leg_top - 1, 0, -1):
        out.px[y] = c.px[y - 1][:]
    out.px[0] = [None] * c.w
    # 腿顶那一行保持原样，免得身子与腿之间裂开一道缝
    out.px[leg_top - 1] = [c.px[leg_top - 1][x] or c.px[leg_top - 2][x] for x in range(c.w)]
    return out


def _hurt(c: Canvas) -> Canvas:
    """受击：往后（左）一缩、往上一挺；眼睛闭上（眼光换成暗面）。"""
    out = c.shifted(-2, -1)
    for y in range(out.h):
        for x in range(out.w):
            v = out.px[y][x]
            if v is not None and v[0] == "eyeglow":
                out.px[y][x] = ("ink", 1)
    return out


def render_beast(beast: Beast) -> tuple[Image.Image, dict[str, list[int]]]:
    mats = Materials.build(beast.ramps)
    idle0 = _canvas_from(beast.idle, beast)
    frames = [
        idle0,
        _breath(idle0, beast.leg_top),
        _canvas_from(beast.attack, beast),
        _hurt(idle0),
        _canvas_from(beast.down, beast),
    ]
    imgs = [to_image(add_outline(f, mats), mats) for f in frames]
    layout = {"idle": [0, 1], "attack": [2], "hurt": [3], "down": [4]}
    return grid_sheet(imgs, len(imgs), beast.w, beast.h), layout


# ===========================================================================
# 元神光球（识海之战）
# ===========================================================================

@dataclass(frozen=True)
class Orb:
    id: str
    name: str
    size: int
    radius: float
    core: tuple[str, str, str, str]   # 由外到内四级色（主色板色名）
    wisp: str
    wisps: int
    phase: float
    note: str = ""


ORBS = (
    Orb("hanli_yuanshen", "韩立元神", 32, 7.5, ("jade1", "jade2", "jade3", "jade4"), "gold4", 3, 0.0,
        "韩立在识海里的元神：青玉色，芯子一点暖白。"),
    Orb("mo_juren_yuanshen", "墨居仁元神", 32, 9.0, ("ink4", "ink6", "stone5", "plaster3"), "jade3", 4, 1.3,
        "夺舍而来的墨居仁元神：灰白冷光，边上绕着几缕青气。"),
    Orb("yu_zitong", "余子童（元神）", 40, 12.5, ("violet0", "violet1", "violet2", "red3"), "red4", 5, 2.1,
        "「比韩立大了有一圈有余」：暗紫、芯子发红的一团，比韩立的光球大一圈半。"),
)


def _orb_frame(orb: Orb, t: int, mode: str) -> Image.Image:
    """画一帧光球。mode: idle（t=0..3 脉动）/ hurt（压扁、偏白）/ down（散成碎光）。

    全部按像素中心取样再量化到色阶，不用 PIL 的抗锯齿，保证每台机器同一结果。
    """
    s = orb.size
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    px = img.load()
    cx = cy = (s - 1) / 2.0
    pulse = [0.0, 0.6, 1.0, 0.6][t % 4]
    r0 = orb.radius * (1.0 + 0.10 * pulse)
    if mode == "hurt":
        r0 = orb.radius * 0.9
    ramp = [P.c(n) for n in orb.core]
    halo_c = P.c(orb.core[1])
    for y in range(s):
        for x in range(s):
            dx, dy = x - cx, y - cy
            if mode == "hurt":
                dx *= 0.85
                dy *= 1.25
            d = math.hypot(dx, dy)
            if mode == "down":
                # 散：外圈碎成点，芯子缩小变淡
                r_core = orb.radius * 0.45
                if d <= r_core:
                    k = d / r_core
                    col = ramp[3] if k < 0.4 else ramp[2]
                    px[x, y] = col + (200,)
                    continue
                ang = math.atan2(dy, dx)
                ring = orb.radius * 1.2
                if abs(d - ring) < 1.0 and (int((ang + math.pi) / (2 * math.pi) * 16) % 3 == 0):
                    px[x, y] = ramp[1] + (170,)
                continue
            if d <= r0:
                k = d / r0
                if k < 0.35:
                    col = ramp[3]
                elif k < 0.62:
                    col = ramp[2]
                elif k < 0.86:
                    col = ramp[1]
                else:
                    col = ramp[0]
                # 左上受光：芯子往左上偏一格的亮斑
                if math.hypot(dx + r0 * 0.35, dy + r0 * 0.35) < r0 * 0.22:
                    col = P.mix(ramp[3], "paper", 0.5)
                if mode == "hurt":
                    col = P.mix(col, "paper", 0.45)
                px[x, y] = col + (255,)
            elif d <= r0 + 3.0:
                # 光晕：三圈逐级变淡（半透明像素，运行时的辉光再把它晕开）
                band = int(d - r0)
                a = (150, 90, 40)[min(2, band)]
                a = int(a * (0.75 + 0.25 * pulse))
                px[x, y] = halo_c + (a,)
    if mode != "down":
        # 绕行的游丝：几个亮点沿椭圆轨道转，每帧转一格
        wc = P.c(orb.wisp)
        for i in range(orb.wisps):
            ang = orb.phase + i * (2 * math.pi / orb.wisps) + t * (math.pi / 8)
            rx, ry = r0 + 2.5, (r0 + 2.5) * 0.55
            wx = int(round(cx + rx * math.cos(ang)))
            wy = int(round(cy + ry * math.sin(ang)))
            for ddx, ddy, a in ((0, 0, 255), (1, 0, 140), (-1, 0, 140), (0, 1, 110), (0, -1, 110)):
                xx, yy = wx + ddx, wy + ddy
                if 0 <= xx < s and 0 <= yy < s:
                    old = px[xx, yy]
                    if old[3] < a:
                        px[xx, yy] = wc + (a,)
    return img


def render_orb(orb: Orb) -> tuple[Image.Image, dict[str, list[int]]]:
    frames = [_orb_frame(orb, t, "idle") for t in range(4)]
    frames.append(_orb_frame(orb, 0, "hurt"))
    frames.append(_orb_frame(orb, 0, "down"))
    layout = {"idle": [0, 1, 2, 3], "hurt": [4], "down": [5]}
    return grid_sheet(frames, len(frames), orb.size, orb.size), layout
