"""非人形 / 特殊敌人的战斗精灵。

敌人站在画面左侧、面朝右边的我方，所以这里的图一律**面朝右**（人形敌人用人物表，
运行时水平翻转；这里的兽与光球不翻）。

每张表一行：待机×2、出招、受击、倒下（光球是 脉动×4、受击、消散）。
待机第二帧、受击帧由第一帧推出来（整体下沉一格 / 往后一缩再闭眼），
出招与倒下各画一张——这两帧的剪影与站姿差得太远，推不出来。

逐一核对 b03–b05 的战斗单位（data/roles 的 name/note）：
  wild_wolf 恶狼            兽：灰狼，压低前身、龇牙
  long_zhong_shou 笼中兽    兽：关久了的活物，怕光见人就扑——瘦、秃斑、惨白的眼
  jiang_shou 僵兽           「走得很慢，两只脚上的分量一样重」：直立佝偻的死物，炼尸炼到一半
  mofu_shigui 墨府尸傀      修仙者斗法留下的遗物：高大的人形死物，残破长袍、锁链、醒过来的眼
  mo_juren_yuanshen 墨居仁元神、yu_zitong 余子童（元神）、hanli_yuanshen 韩立元神：
                            识海之战里的光球；余子童「比韩立大了有一圈有余」→ 40 见方
  hei_xiong 黑熊是人（铁拳会头目），走人物表；qu_hun 曲魂是巨汉，同样走人物表（24×32）。
  ye_zhu 野猪（野外遭遇 be03–be05，改编）：敦实、鬃毛、獠牙，出招是低头一撞。

第 7 章（docs/ch07-design.md 第 5、8 节）的六个非人形：
  zichi_bishe 紫翅碧蛇、chuanshan_shou 穿山甲兽  战斗② 络腮胡子放出来的两头灵兽
  mo_jiao 墨蛟              战斗⑤：蜕了皮的白蛟，40×32，比别的兽大一号
  tuishan_shou 推山兽       环形山遭遇：石皮巨猪，36×28，比野猪大一圈
  tiebi_yuan 铁臂猿         环形山遭遇、支线东坡石屋：铁灰前臂的大猿，32×32
  huoyan_shu 火焰鼠         环形山遭遇：小兽，画在 32×24 里只占一角
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from PIL import Image

import palette as P
from sprites_core import Canvas, Materials, add_outline, cloth_ramp, grid_sheet, to_image, tpl


@dataclass(frozen=True)
class Beast:
    id: str
    name: str
    w: int
    h: int
    idle: tuple[str, ...]
    attack: tuple[str, ...]
    down: tuple[str, ...]
    ramps: dict[str, list[tuple[int, int, int]]]
    codes: dict[str, tuple[str, int]]
    leg_top: int          # 待机呼吸时，这一行以上整体下沉
    note: str = ""


def _codes(extra: dict[str, tuple[str, int]] | None = None) -> dict[str, tuple[str, int]]:
    base = {
        "A": ("fur", 3), "B": ("fur", 2), "C": ("fur", 1), "D": ("fur", 0),
        "E": ("belly", 3), "F": ("belly", 2), "G": ("belly", 1),
        "e": ("eyeglow", 3), "n": ("ink", 1), "W": ("tooth", 3), "r": ("mouth", 2),
        "k": ("claw", 2),
    }
    if extra:
        base.update(extra)
    return base


# ===========================================================================
# 恶狼
# ===========================================================================

WOLF_IDLE = tpl("""
................................
................................
......................A..A......
.....................AB.AB......
....................ABBBBBBB....
.............D.D.D.ABBBBBeBBB...
...........DDADADADBBBBBBBBBBBn.
........AAABBBBBBBBBBBBBBCWWWW..
......AABBBBBBBBBBBBBBBBCrrrr...
.....ABBBBBBBBBBBBBBBBBCWWWW....
....ABBBBBBBBBBBBBBBBBCCCCC.....
...AB.BBBBFFFFFFFFBBBBC.........
..AB..CBBBGGGGGGGGBBBC..........
..B...CBBC.......CBBC...........
......CBBC.......CBBDC..........
.....CBC.DC......CBC.DC.........
.....CBC.DC......CBC.DC.........
.....CB..DC......CBC.DC.........
......CB.DC......CBC..DC........
......CB.DC......CBC..DC........
......CB.DC......CBC..DC........
......kkkDkk.....kkk..Dkk.......
................................
................................
""")
WOLF_ATTACK = tpl("""
................................
................................
................................
........................A..A....
.......................AB.AB....
..............D.D.D...ABBBBBB...
............DDADADADABBBBBeBBB..
....AAAAAAABBBBBBBBBBBBBBBBBBBBn
..AABBBBBBBBBBBBBBBBBBBBBBBCWWWW
.ABBBBBBBBBBBBBBBBBBBBBBBBCrrrr.
AB.CBBBBFFFFFFFFFBBBBBBBBCrrr...
B..CCBBBGGGGGGGGGGBBBBBBCWWWW...
....CCBBBC.......CBBBBBC........
...CBBC.DC........CBBBBC........
..CBC...DC.........CBBDBC.......
.CBC.....DC.........CBC.DC......
CBC.......DC.........CBC.DC.....
kk........Dkk.........kkk.Dkk...
................................
................................
................................
................................
................................
................................
""")
WOLF_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
....................A..A........
..............DDDD.AB.ABB.......
......AAAAAAAABBBBBBBBBBBBB.....
...AABBBBBBBBBBBBBBBBBBBBBBBBn..
..ABBBBFFFFFFFFFBBBBBBBCCCCCC...
.ABCCCCGGGGGGGGGCCBBBBCC........
.B..CDCDC...CDCDC..DCC..........
........................kk......
................................
................................
""")

WOLF = Beast(
    id="wild_wolf", name="恶狼", w=32, h=24,
    idle=tuple(WOLF_IDLE), attack=tuple(WOLF_ATTACK), down=tuple(WOLF_DOWN),
    ramps={
        # 深灰狼：背上一道更暗的鬃（D），眼是两格亮金——在暗的战斗背景上先看见的就是那双眼
        "fur": [P.c("ink1"), P.mix("stone0", "ink3", 0.3), P.mix("stone1", "stone2", 0.3), P.c("stone3")],
        "belly": [P.c("stone2"), P.c("stone3"), P.c("stone4"), P.c("stone5")],
        "eyeglow": [P.c("gold1"), P.c("gold2"), P.c("gold3"), P.mix("gold4", "paper", 0.3)],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red2"), P.c("red2")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
    },
    codes=_codes(), leg_top=14,
    note="教学关的普通野兽：灰狼，抬头竖耳、张嘴龇牙、颈背鬃毛竖起、收腹长腿。",
)

# ===========================================================================
# 笼中兽：同是四足，但瘦、弓背、秃斑、惨白的眼——关久了怕光
# ===========================================================================

CAGE_IDLE = tpl("""
................................
................................
................................
................................
................................
...........AAAAAA...............
.........AABBBBBBAA.............
.......AABBBSSBBBBBAA.....A.A...
......ABBBBSSSBBBBBBBA...AB.AB..
.....ABBBBBBSBBBBBBBBBAAABBBBB..
....ABBBABABABABBBBBBBBBBBBBeeB.
...AB.CBBABABABABBBBBBBBBBBBBBB.
..AB..CBBBBBBBBBBBBBBBBBBBBBBBBn
..B...CBBGGGGGGGBBBCBBBBBBCrWrW.
......CBBC.......CBBC..CCCWrWr..
......CBC.DC.....CBC.DC.........
.....CBC..DC.....CBC.DC.........
.....CB...DC.....CB..DC.........
.....CB...DC.....CB..DC.........
....CB....DC....CB...DC.........
....kk...Dkk....kk..Dkk.........
................................
................................
................................
""")
CAGE_ATTACK = tpl("""
................................
................................
................................
................................
............AAAAAA..............
..........AABBBBBBAA.......A.A..
........AABBBSSBBBBBAA....AB.AB.
.......ABBBBSSSBBBBBBBAAAABBBBB.
.....AABBBBBBSBBBBBBBBBBBBBBeeB.
...AABBBABABABABBBBBBBBBBBBBBBBn
..AB.CBBABABABABBBBBBBBBBBCrWrW.
.AB..CBBBBBBBBBBBBBBBBBBCCrrrr..
.B...CCBGGGGGGGBBBBBBBBCCWrWr...
.....CBBC........CBBBBCC........
....CBC.DC........CBBDBC........
...CBC...DC........CBC.DC.......
..CBC.....DC........CBC.DC......
.CBC.......DC........CBC.DC.....
.kk........Dkk.......kkk.Dkk....
................................
................................
................................
................................
................................
""")
CAGE_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........AAAAAAAA.............
........AAABBBSBBBBAAA..........
......AABBBBSSSBBBBBBBBA........
....AABBBBBBBSBBBBBBBBBBBA......
...ABBBBGGGGGGGGBBBBBBBCBBBn....
..ABCCCCGGGGGGGGCCBBBBCCCCC.....
..BC.DCDC...DCDC..DCCC..........
.......................kk.......
................................
................................
................................
""")

CAGE = Beast(
    id="long_zhong_shou", name="笼中兽", w=32, h=24,
    idle=tuple(CAGE_IDLE), attack=tuple(CAGE_ATTACK), down=tuple(CAGE_DOWN),
    ramps={
        # 弓着的背上一排肋骨（受光色画的横纹）要看得见，所以受光面比恶狼拉得更开
        "fur": [P.c("ink1"), P.mix("stone0", "violet0", 0.3), P.mix("stone1", "violet1", 0.2), P.mix("stone3", "violet2", 0.15)],
        "belly": [P.mix("skin0", "stone1", 0.5), P.mix("skin1", "stone2", 0.5), P.mix("skin1", "stone3", 0.4), P.mix("skin2", "stone4", 0.4)],
        "patch": [P.mix("skin0", "stone1", 0.4), P.mix("skin1", "stone2", 0.45), P.mix("skin2", "stone3", 0.45), P.mix("skin2", "stone4", 0.3)],
        "eyeglow": [P.c("gold2"), P.c("gold3"), P.mix("gold4", "paper", 0.5), P.c("paper")],
        "tooth": [P.c("stone4"), P.c("stone5"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red0"), P.c("red1"), P.c("red1")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
    },
    codes=_codes({"S": ("patch", 2)}), leg_top=14,
    note="暗道笼子里关久了的活物（怕光、见人就扑）：背弓得老高、头垂得比肩低、一排肋骨、秃斑、惨白的眼。与恶狼同为四足，剪影是饿坏了的那一种。",
)

# ===========================================================================
# 僵兽：直立佝偻，两条长臂垂着，一身死人皮色，缠着烂布条
# ===========================================================================

STIFF_IDLE = tpl("""
................................
................................
................................
................................
................................
................................
..........AAAA..................
........AABBBBAA................
.......ABBBBBBBBA...............
......ABBBBBBBBBBAAA............
......ABBBBBBBBBBBBBAA..........
.....ABBBBBBBBBBBBBBBBAAA.......
.....ABBBBBBBBBBBBBBBBBBBA......
.....CBBBBBBBBBBBBBBBBBeBBB.....
.....CBBBBBBBBBBBBBBBBBBBBBC....
.....CBBBBBBBBBBCBBBBBBBnWWC....
......CBBBBBBBBC.CBBBBBCCC......
......CBBBBBBBC...CBBBC.........
.......CBBBBBC.....CBBC.........
.......TTTTTTT.....CBTC.........
.......CBBBBBC.....CBTC.........
......CBBBCBBBC....CBBC.........
......CBBC.CBBC....CBBBC........
.....CBBC...CBBC...kCkCk........
.....CBC.....CBC................
.....CBC.....CBBC...............
....CBBC......CBC...............
....kkk.......kkk...............
................................
................................
................................
................................
""")
STIFF_ATTACK = tpl("""
................................
................................
................................
................................
................................
................................
................................
..........AAAA..................
........AABBBBAA................
.......ABBBBBBBBA...............
......ABBBBBBBBBBAAAA...........
......ABBBBBBBBBBBBBBAAAA.......
.....ABBBBBBBBBBBBBBBBBBBA......
.....CBBBBBBBBBBBBBBBBBBeBBB....
.....CBBBBBBBBBBBBBBBBBBBBBBC...
.....CBBBBBBBBBBBBAAAAAAnWWWCk..
......CBBBBBBBBCBBBBBBBBBBBTTkk.
......CBBBBBBBCCCCCCCCCCCCCCk...
.......CBBBBBC..................
.......TTTTTTT..................
.......CBBBBBC..................
......CBBBCBBBC.................
.....CBBC...CBBC................
....CBBC.....CBBC...............
...CBBC.......CBC...............
...CBC........CBBC..............
..CBBC.........CBC..............
..kkk..........kkk..............
................................
................................
................................
................................
""")
STIFF_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............AAAAAA............
..........AAAABBBBBBAA..........
.......AAABBBBBBBBBBBBA.........
.....AABBBBBTTBBBBBBBBBBA.......
....ABBBBBBBTTBBBBBBBBBBBBAA....
...ABBBBBBBBBBBBBBBBBBBBBBBBn...
..kBCCCCCCCCBBBBBBBBBCCCCCCC....
..kk.CBC..CBBCCCCCCCCCkCk.......
.....kkk..kkk...................
................................
""")

STIFF = Beast(
    id="jiang_shou", name="僵兽", w=32, h=32,
    idle=tuple(STIFF_IDLE), attack=tuple(STIFF_ATTACK), down=tuple(STIFF_DOWN),
    ramps={
        "fur": cloth_ramp(P.mix("stone2", "jade1", 0.35)),
        "wrap": [P.c("stone1"), P.c("stone2"), P.c("stone3"), P.c("stone4")],
        "eyeglow": [P.c("jade2"), P.c("jade3"), P.c("jade4"), P.c("paper")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
        "belly": cloth_ramp(P.c("stone3")),
        "tooth": [P.c("stone4"), P.c("stone5"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red0"), P.c("red1"), P.c("red1")],
    },
    codes=_codes({"T": ("wrap", 2)}), leg_top=23,
    note="墨大夫炼尸术试到一半的活物：直立、佝偻、长臂垂爪、青灰死人皮、身上缠着烂布条；眼里一点幽绿。",
)

# ===========================================================================
# 墨府尸傀：高大人形，残破长袍，腕上断锁链，眼里醒过来的一点光
# ===========================================================================

SHIGUI_IDLE = tpl("""
................................
................................
................................
................................
............SSSS................
...........SSSSSS...............
..........SSSSSSSS..............
..........SkeSSekS..............
..........SSSSSSSs..............
...........sSSSSs...............
.........AABBTTBBAA.............
.......AABBBBTTBBBBAA...........
......ABBBBBBTTBBBBBBA..........
......ABBBBBBTTBBBBBBC..........
......ABBBBBBBTBBBBBBC..........
......ABBCBBBBBBBBCBBC..........
.....ABBCCBBBBBBBBCCBBC.........
.....ABBC.BBBBBBBBC.BBC.........
.....ABC..YYYYYYYYC..BC.........
.....SSs..BBBBBBBBC..Ss.........
.....SsZ..BBBBBBBBC..sZ.........
......ZZ..BBBBCBBBC..ZZ.........
.......Z..BBBBCBBBBC..Z.........
.......Z..BBBBCBBBBC..Z.........
.........ABBBBCBBBBC............
.........ABBBBCCBBBBC...........
.........ABBBC.CBBBBC...........
.........ABBB..CBBBBC...........
.........ABBC...CBBBC...........
........ABBC....CBBBBC..........
........ABBC.....CBBBC..........
........BBCC.....CCBBC..........
........B.C.......C.B...........
.........ss.......ss............
........ssk.......ssk...........
................................
................................
................................
................................
................................
""")
SHIGUI_ATTACK = tpl("""
................................
................................
................................
................................
................................
................................
.............SSSS...............
............SSSSSS..............
...........SSSSSSSS.............
...........SkeSSekS.............
...........SSSSSSSs.............
............sSSSSs..............
..........AABBTTBBAAAA..........
........AABBBBTTBBBBBBAAAAAASs..
.......ABBBBBBTTBBBBBBBBBBBBSsZ.
.......ABBBBBBTTBBBBBBBBBCCC..ZZ
.......ABBBBBBBTBBBBBBC.......Z.
......ABBCBBBBBBBBCBBC..........
......ABBCCBBBBBBBBCCBC.........
......ABBC.BBBBBBBBC.BC.........
......ABC..YYYYYYYYC.BC.........
......SSs..BBBBBBBBC.Ss.........
......SsZ..BBBBBBBBC.sZ.........
.......ZZ..BBBBCBBBC.ZZ.........
........Z..BBBBCBBBBC.Z.........
..........ABBBBCBBBBC...........
.........ABBBBC.CBBBBC..........
........ABBBBC...CBBBBC.........
.......ABBBC......CBBBBC........
......ABBBC........CBBBC........
......BBCC..........CCBBC.......
......B.C............C.B........
......ss..............ss........
.....ssk..............ssk.......
................................
................................
................................
................................
................................
................................
""")
SHIGUI_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............SSSS................
..........AASSSSSSAA............
........AABBSkSSekBBAA..........
.......ABBBBSSSSSSBBBBBA........
......ABBBBBBTTBBBBBBBBBBA......
.....ABBBBBBBBTTBBBBBBBBBBBA....
....ABBYYYYYYYYYYBBBBBBBBBBBBA..
...SsBBBBBBBBBBBBBBBBBCCCCCCCC..
..ZZsCCCCCCCCCCCCCCCCCCC..ss....
..Z....................ssk......
................................
................................
................................
................................
""")

SHIGUI = Beast(
    id="mofu_shigui", name="墨府尸傀", w=32, h=40,
    idle=tuple(SHIGUI_IDLE), attack=tuple(SHIGUI_ATTACK), down=tuple(SHIGUI_DOWN),
    ramps={
        "fur": cloth_ramp(P.mix("ink3", "violet0", 0.35)),      # 残破的深色长袍
        "trimrag": cloth_ramp(P.mix("stone2", "gold0", 0.2)),
        "corpse": cloth_ramp(P.mix("stone3", "jade1", 0.35)),
        "eyeglow": [P.c("red2"), P.c("red3"), P.c("red4"), P.c("gold4")],
        "chain": [P.c("ink2"), P.c("ink3"), P.c("ink5"), P.c("ink6")],
        "belt": cloth_ramp(P.mix("wood1", "ink2", 0.4)),
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
        "belly": cloth_ramp(P.c("stone3")),
        "tooth": [P.c("stone4"), P.c("stone5"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red0"), P.c("red1"), P.c("red1")],
    },
    codes=_codes({
        "S": ("corpse", 2), "s": ("corpse", 1), "T": ("trimrag", 2), "Y": ("belt", 2),
        "Z": ("chain", 2), "k": ("corpse", 0),
    }),
    leg_top=24,
    note="修仙者斗法留下的遗物、封在马厩地窖里：比人高、残破深色长袍、死人皮、腕上断链、醒过来的一对红眼。",
)

# ===========================================================================
# 野猪：前重后轻的楔形身子、肩上一溜鬃毛、脸颊一道暗线把头分出来、长嘴拱鼻、上翘的白獠牙
# ===========================================================================

BOAR_IDLE = tpl("""
................................
................................
................................
................................
................................
...........D.D.D.D..............
.........DDADADADADA............
.......AABBBBBBBBBBBBA...A......
.....AABBBBBBBBBBBBBBBAAABA.....
....ABBBBBBBBBBBBBBBBBBBBBBA....
...ABBBBBBBBBBBBBBBBBBCBBBBBA...
..AB.BBBBBBBBBBBBBBBBBCBBeBBBA..
..B..CBBBBBBBBBBBBBBBBBCBBBBWBn.
.....CBBBBBBBBBBBBBBBBBBCBBBWnnn
.....CBBBBBBBBBBBBBBBBBBBCCCCC..
.....CCBBBFFFFFFFFFBBBBBC.......
......CCGGGGGGGGGGGGCBCC........
......DCBC.DCBC....DCBC.DCBC....
......DCBC.DCBC....DCBC.DCBC....
......DCB..DCB.....DCB..DCB.....
......Dkk..Dkk.....Dkk..Dkk.....
................................
................................
................................
""")
BOAR_ATTACK = tpl("""
................................
................................
................................
................................
................................
................................
..........D.D.D.D...............
........DDADADADADA.............
......AABBBBBBBBBBBBA...........
....AABBBBBBBBBBBBBBBAA..A......
..AABBBBBBBBBBBBBBBBBBBAABA.....
.ABBBBBBBBBBBBBBBBBBBBBBCBBBA...
.B..CBBBBBBBBBBBBBBBBBBBCBeBBBA.
....CBBBBBBBBBBBBBBBBBBBBCBBBWBn
....CBBBBBBBBBBBBBBBBBBBBBCBBWnn
....CCBBFFFFFFFFFFBBBBBBBBCCCCC.
.....CCGGGGGGGGGGGGGCBBCC.......
...DCBC.......DCBC...DCBC.DCBC..
..DCBC.........DCBC...DCBC.DCBC.
.DCB............DCB....DCB..DCB.
Dkk..............Dkk....Dkk..Dkk
................................
................................
................................
""")
BOAR_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............D.D.D...............
..........DDADADADA...A.........
.......AABBBBBBBBBBBAAABA.......
....AABBBBBBBBBBBBBBBBBBBCBA....
...ABBBBBFFFFFFFFFBBBBBBBCBBWBn.
..ABCCCGGGGGGGGGGGCCBBBBBCBBWnn.
..BC.DCBC.DCBC..DCBC.DCBCCCCCC..
................................
................................
................................
................................
""")

BOAR = Beast(
    id="ye_zhu", name="野猪", w=32, h=24,
    idle=tuple(BOAR_IDLE), attack=tuple(BOAR_ATTACK), down=tuple(BOAR_DOWN),
    ramps={
        "fur": [P.c("ink1"), P.mix("wood0", "ink2", 0.35), P.mix("wood1", "stone1", 0.45), P.mix("wood2", "stone2", 0.45)],
        "belly": [P.mix("wood1", "stone1", 0.5), P.mix("wood2", "stone2", 0.5), P.mix("wood3", "stone3", 0.5), P.mix("wood4", "stone4", 0.5)],
        "eyeglow": [P.c("red1"), P.c("red2"), P.c("red3"), P.c("red4")],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red1"), P.c("red2")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.mix("skin0", "ink2", 0.5), P.c("ink3")],
    },
    codes=_codes(), leg_top=17,
    note="野外遭遇的山林野兽（改编）：敦实、肩上鬃毛竖起、白獠牙上翘；出招是低头一撞（role note）。",
)

# ===========================================================================
# 紫翅碧蛇：碧绿的蛇身盘在地上、前半身立起，背上一对紫色肉翅
# ===========================================================================

BISHE_IDLE = tpl("""
................................
................................
......V.........................
.....VUV........................
.....VUUV.....V......AAAA.......
......VUUV...VUV....ABBBBBA.....
......VUXUV.VUUV...ABBBBeBBBA...
.......VUXUVUXUV...ABBBBBBBBBWn.
........VUXUUXUV..ABBBBBBCrrrrt.
.........VUUUUV..ABBBBBCCWWWC..t
..........VVVV..ABBBBCCCCCC.....
...............ABBBBC...........
..............ABBBBC............
.............ABBBBC.............
.......AAAAAABBBBBC.............
.....AABBBBBBBBBBBBAAAA.........
....ABBBBBBBBBBBBBBBBBBAA.......
...ABBBBCCCCCCCCCCBBBBBBBA......
.A.ABBBBBBBBBBBBBBBBCBBBBB......
AB.CFFFFFFFFFFFFFFFFFCBBBC......
CBACGGGGGGGGGGGGGGGGGGCCC.......
.CCDDDDDDDDDDDDDDDDDDDD.........
................................
................................
""")
BISHE_ATTACK = tpl("""
.....V..........................
....VUV.......V.................
....VUUV.....VUV................
.....VUUV...VUUV................
.....VUXUV.VUXUV................
......VUXUVUXUUV................
.......VUXUUXUV.......AAAA......
........VUUUUV......AABBBBBAA...
.........VVVV......ABBBBBeBBBA..
................AAABBBBBBBBBBWWn
..............AABBBBBBBBCrrrrrtt
.............ABBBBBBBCCCWWWWr..t
............ABBBBBBCC...........
...........ABBBBBC..............
.......AAAABBBBBC...............
.....AABBBBBBBBBBAAAA...........
....ABBBBBBBBBBBBBBBBAA.........
...ABBBBCCCCCCCCCBBBBBBA........
.A.ABBBBBBBBBBBBBBBBCBBBB.......
AB.CFFFFFFFFFFFFFFFFFCBBC.......
CBACGGGGGGGGGGGGGGGGGGCC........
.CCDDDDDDDDDDDDDDDDDDDD.........
................................
................................
""")
BISHE_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..........VVV...................
........VVUUUVV.................
......VVUUXUUUUVV...............
....AAAAAAAAAAAAAAAAA...AAAA....
..AABBBBBBBBBBBBBBBBBAAABBnBBA..
.ABBBBBBBBBBBBBBBBBBBBBBBBBBBBn.
.CFFFFFFFFFFFFFFFFFFFFFFFCCCCC..
..CGGGGGGGGGGGGGGGGGGGGCC.......
................................
""")

BISHE = Beast(
    id="zichi_bishe", name="紫翅碧蛇", w=32, h=24,
    idle=tuple(BISHE_IDLE), attack=tuple(BISHE_ATTACK), down=tuple(BISHE_DOWN),
    ramps={
        "fur": [P.mix("jade0", "ink1", 0.45), P.c("jade1"), P.c("jade2"), P.c("jade3")],
        "belly": [P.mix("jade2", "soil3", 0.5), P.mix("jade3", "soil4", 0.5), P.mix("jade3", "plaster1", 0.5),
                  P.mix("jade4", "plaster2", 0.5)],
        "wing": [P.c("violet0"), P.c("violet1"), P.c("violet2"), P.c("violet3")],
        "eyeglow": [P.c("gold1"), P.c("gold2"), P.c("gold3"), P.mix("gold4", "paper", 0.3)],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red2"), P.c("red3")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
    },
    codes=_codes({"V": ("wing", 1), "U": ("wing", 2), "X": ("wing", 3), "t": ("mouth", 3)}), leg_top=14,
    note="络腮胡子放出来的灵兽：碧绿的蛇身盘在地上、前半身立起，背上一对紫色肉翅；出招是扑咬，舌信吐在外头。",
)

# ===========================================================================
# 穿山甲兽：拱背、一身交叠的鳞甲、尖长的嘴、粗尾拖地、短腿大爪
# ===========================================================================

CHUANSHAN_IDLE = tpl("""
................................
................................
................................
................................
................................
................................
.............AAAAAA.............
..........AAABBBBBBAAA..........
........AABBCABBBCABBBAA........
.......ABBCABBBCABBBCABBBA......
......ABBCABBBCABBBCABBBBBA.....
.....ABBCABBBCABBBCABBBBCABA....
....ABBCABBBCABBBCABBBBCABBBA...
...ABBCABBBCABBBCABBBBCABBBBAA..
..ABBCABBBCABBBCABBBBCABBBeBBBn.
.ABBCCBBBCCBBBCCBBBBCCBBBBBBBnn.
ABBCCFFFFFFFFFFFFFFFFFCBBBCCC...
BCC..CGGGGGGGGGGGGGGGCC.........
C....CBBC.CBBC....CBBC.CBBC.....
.....CBBC.CBBC....CBBC.CBBC.....
.....Dkkk.Dkkk....Dkkk.Dkkk.....
................................
................................
................................
""")
CHUANSHAN_ATTACK = tpl("""
................................
................................
................................
................................
................................
..............AAAAAA............
...........AAABBBBBBAAA.........
.........AABBCABBBCABBBAA.......
........ABBCABBBCABBBCABBBA.....
.......ABBCABBBCABBBCABBBBBA....
......ABBCABBBCABBBCABBBBCABAA..
.....ABBCABBBCABBBCABBBBCABBeBBn
....ABBCABBBCABBBCABBBBCABBBBBnn
...ABBCCBBBCCBBBCCBBBBCCBBBCCC..
..ABBCCFFFFFFFFFFFFFFFFCBBBC....
.ABCC.CGGGGGGGGGGGGGGGCCBBBC....
.BC...CBBC.CBBC.......CBBBBBkk..
BC....CBBC.CBBC........CBBBkkkk.
C.....CBBC.CBBC..........Ckk.kk.
......CBBC.CBBC.................
......Dkkk.Dkkk.................
................................
................................
................................
""")
CHUANSHAN_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........AAAAAAAA.............
.........AABBCABBBCAA...........
........ABBCABBBCABBBA..........
.......ABBCABBBCABBBCABA........
.......ABCABBBCABBBCABBBA.......
......ABBCABBBCABBBCABBBA.......
......CBCCBBBCCBBBCCBBBCC.......
.......CCFFFFFFFFFFFFFCC........
.........CCGGGGGGGGGCC..........
................................
""")

CHUANSHAN = Beast(
    id="chuanshan_shou", name="穿山甲兽", w=32, h=24,
    idle=tuple(CHUANSHAN_IDLE), attack=tuple(CHUANSHAN_ATTACK), down=tuple(CHUANSHAN_DOWN),
    ramps={
        "fur": [P.mix("soil0", "ink1", 0.4), P.c("soil2"), P.mix("soil3", "gold1", 0.35), P.mix("soil4", "gold2", 0.4)],
        "belly": [P.c("soil2"), P.c("soil3"), P.mix("soil4", "skin1", 0.4), P.mix("soil5", "skin2", 0.4)],
        "eyeglow": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red1"), P.c("red2")],
        "claw": [P.c("ink1"), P.mix("stone1", "ink2", 0.5), P.c("stone2"), P.c("stone3")],
        "ink": [P.c("ink0"), P.c("ink1"), P.mix("soil1", "ink2", 0.5), P.c("ink3")],
    },
    codes=_codes(), leg_top=18,
    note="络腮胡子的另一头灵兽：拱背、一身交叠的土黄鳞甲、尖长的嘴、粗尾拖地、短腿大爪；出招是人立起来抡爪；倒下时缩成一团。",
)

# ===========================================================================
# 墨蛟：蜕了皮的雪白蛟身盘在泥里、前半身昂起，头上一对角、一只前爪；出招吐紫液
# ===========================================================================

MOJIAO_IDLE = tpl("""
........................................
........................................
........................................
...........................H....H.......
...........................HH...HH......
............................HH..HH......
..........................AAAAAAAAA.....
.........................ABBBBBBBBBAA...
........................ABBBBBBBeBBBBA..
........................ABBBBBBBBBBBBBBn
.......................ABBBBBBBBCrrrWWn.
.......................ABBBBBBCCCWWWW...
.................D.D.D.ABBBBBBC.........
...............DDADADABBBBBBBC..........
..............ABBBBBBBBBBBBBC...........
.............ABBBBBBBBBBBBBC..kk........
............ABBBBBFFFFFBBBBCkkBBk.......
............ABBBBFGGGGGFBBBBBBBBC.......
............CBBBBFG...GFBBBBBBBC........
.............CBBBBFF..FFBBBBCC..........
..............CBBBBBF...................
.......AAAAAAAABBBBBBF..................
.....AABBBBBBBBBBBBBBBBAAAA.............
....ABBBBBBBBBBBBBBBBBBBBBBAA...........
...ABBBBBCCCCCCCCCCCCBBBBBBBBA..........
...ABBBBBBBBBBBBBBBBBBBBCBBBBBA.....AA..
....CFFFFFFFFFFFFFFFFFFFFCBBBBBAAAAABBA.
.....CGGGGGGGGGGGGGGGGGGGGCBBBBBBBBBBCC.
......DDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC...
........................................
........................................
........................................
""")
MOJIAO_ATTACK = tpl("""
........................................
........................................
.........................H....H.........
.........................HH...HH........
..........................HH..HH........
........................AAAAAAAAA.......
.......................ABBBBBBBBBAA.....
......................ABBBBBBBeBBBBA....
......................ABBBBBBBBBBBBBBWn.
.....................ABBBBBBBBCrrrrrW..P
.....................ABBBBBBBCrrrrr...PQ
.....................ABBBBBBCCWWWWWn.PQQ
...............D.D.D.ABBBBBBC.......PQQP
.............DDADADABBBBBBBC.........QP.
............ABBBBBBBBBBBBBC.............
...........ABBBBBBBBBBBBBC..kk..........
..........ABBBBBFFFFFBBBBCkkBBk.........
..........ABBBBFGGGGGFBBBBBBBBC.........
..........CBBBBFG...GFBBBBBBBC..........
...........CBBBBFF..FFBBBBCC............
............CBBBBBF.....................
.......AAAAAABBBBBBF....................
.....AABBBBBBBBBBBBBBBAAAA..............
....ABBBBBBBBBBBBBBBBBBBBBAA............
...ABBBBBCCCCCCCCCCCCBBBBBBBA...........
...ABBBBBBBBBBBBBBBBBBBBCBBBBA......AA..
....CFFFFFFFFFFFFFFFFFFFFCBBBBAAAAAABBA.
.....CGGGGGGGGGGGGGGGGGGGGCBBBBBBBBBBCC.
......DDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC...
........................................
........................................
........................................
""")
MOJIAO_DOWN = tpl("""
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
..............................H..H......
...............................H..H.....
.........AAAAAAAAAAAAAAAAAAAAAAAAAAA....
......AABBBBBBBBBBBBBBBBBBBBBBBBBBBBAA..
....AABBBBBBBBBBBBBBBBBBBBBBBBBBBnBBBBn.
...ABBBBCCCCCCCCCCBBBBBBBBBBBBBBBBBBBn..
...CFFFFFFFFFFFFFFFFFFFFFFFFFFCCkkCCC...
....CGGGGGGGGGGGGGGGGGGGGGGGGGCC........
.....DDDDDDDDDDDDDDDDDDDDDDDDDD.........
........................................
........................................
""")

MOJIAO = Beast(
    id="mo_jiao", name="墨蛟", w=40, h=32,
    idle=tuple(MOJIAO_IDLE), attack=tuple(MOJIAO_ATTACK), down=tuple(MOJIAO_DOWN),
    ramps={
        "fur": [P.mix("water1", "ink1", 0.5), P.mix("stone3", "water3", 0.45), P.c("plaster2"), P.c("paper")],
        "belly": [P.mix("stone3", "gold2", 0.3), P.mix("stone4", "gold3", 0.3), P.mix("plaster1", "gold3", 0.25),
                  P.mix("plaster2", "gold4", 0.2)],
        "horn": [P.c("ink1"), P.c("ink2"), P.mix("stone1", "ink3", 0.4), P.c("stone2")],
        "venom": [P.c("violet0"), P.c("violet1"), P.c("violet2"), P.c("violet3")],
        "eyeglow": [P.c("red1"), P.c("red2"), P.c("red3"), P.c("red4")],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red2"), P.c("red2")],
        "claw": [P.c("ink1"), P.mix("stone1", "ink2", 0.5), P.c("stone2"), P.c("stone3")],
        "ink": [P.c("ink0"), P.c("ink1"), P.mix("stone1", "ink2", 0.5), P.c("ink3")],
    },
    codes=_codes({"H": ("horn", 2), "P": ("venom", 2), "Q": ("venom", 3)}), leg_top=21,
    note="地下沼泽的墨蛟，蜕了皮之后通身雪白：蛟身盘在泥里、前半身昂起，头上一对角、一只前爪；出招张口吐一团紫液；倒下时整条摊平。",
)

# ===========================================================================
# 推山兽：几丈高的巨型野猪，背上一层石皮——比野猪大一圈，石板一块压一块
# ===========================================================================

TUISHAN_IDLE = tpl("""
....................................
....................................
....................................
....................................
..............RR..RR................
..........RR.RSSRRSSR.RR............
........RRSSRSSSSSSSSRSSRR..........
......AASSSSSSQSSSSQSSSSSSAA..A.....
.....ABBBSQSSSSSSQSSSSSQSBBAAABA....
....ABBBBBBBBBBBBBBBBBBBBBBBBBBBA...
...ABBBBBBBBBBBBBBBBBBBBBBCBBBBBBA..
..ABBBBBBBBBBBBBBBBBBBBBBBCBBeBBBA..
..B.BBBBBBBBBBBBBBBBBBBBBBBCBBBBWBn.
....CBBBBBBBBBBBBBBBBBBBBBBCBBBWWnnn
....CBBBBBBBBBBBBBBBBBBBBBBBCBBWW...
....CBBBBBBBBBBBBBBBBBBBBBBBBCCCCC..
....CCBBBBFFFFFFFFFFFFBBBBBBC.......
.....CCGGGGGGGGGGGGGGGGGCBBCC.......
.....DCBBC..DCBBC.....DCBBC.DCBBC...
.....DCBBC..DCBBC.....DCBBC.DCBBC...
.....DCBBC..DCBBC.....DCBBC.DCBBC...
.....DCBB...DCBB......DCBB..DCBB....
.....Dkkk...Dkkk......Dkkk..Dkkk....
....................................
....................................
....................................
....................................
....................................
""")
TUISHAN_ATTACK = tpl("""
....................................
....................................
....................................
....................................
....................................
.............RR..RR.................
.........RR.RSSRRSSR.RR.............
.......RRSSRSSSSSSSSRSSRR...........
.....AASSSSSSQSSSSQSSSSSSAA.........
....ABBBSQSSSSSSQSSSSSQSBBBAA..A....
...ABBBBBBBBBBBBBBBBBBBBBBBBBAABA...
..ABBBBBBBBBBBBBBBBBBBBBBBBBCBBBBA..
.ABBBBBBBBBBBBBBBBBBBBBBBBBBCBeBBBA.
.B..CBBBBBBBBBBBBBBBBBBBBBBBBCBBBWBn
....CBBBBBBBBBBBBBBBBBBBBBBBBBCBBWnn
....CBBBBBBBBBBBBBBBBBBBBBBBBBBCWWn.
....CCBBBFFFFFFFFFFFBBBBBBBBBCCCC...
.....CCGGGGGGGGGGGGGGGCBBBBBC.......
...DCBBC.........DCBBC..DCBBC.DCBBC.
..DCBBC...........DCBBC..DCBBC.DCBBC
.DCBBC.............DCBBC..DCBBC.DCBB
DCBB................DCBB...DCBB..DCB
Dkkk................Dkkk....Dkkk..Dk
....................................
....................................
....................................
....................................
....................................
""")
TUISHAN_DOWN = tpl("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
..............RR..RR................
..........RR.RSSRRSSR.RR............
.......RRSSRSSSSSSSSRSSRRA..A.......
.....AASSSSSSQSSSSQSSSSSSBAABA......
...AABBBBBBBBBBBBBBBBBBBBBBBBCBA....
..ABBBBBBFFFFFFFFFFBBBBBBBBBBCBBWBn.
.ABCCCGGGGGGGGGGGGGCCBBBBBBBBCBBWnn.
.BC.DCBBC.DCBBC..DCBBC.DCBBCCCCCC...
....................................
....................................
....................................
....................................
....................................
....................................
""")

TUISHAN = Beast(
    id="tuishan_shou", name="推山兽", w=36, h=28,
    idle=tuple(TUISHAN_IDLE), attack=tuple(TUISHAN_ATTACK), down=tuple(TUISHAN_DOWN),
    ramps={
        "fur": [P.c("ink1"), P.mix("wood0", "stone0", 0.5), P.mix("wood1", "stone1", 0.55), P.mix("wood2", "stone2", 0.55)],
        "belly": [P.mix("wood1", "stone1", 0.5), P.mix("wood2", "stone2", 0.5), P.mix("wood3", "stone3", 0.5),
                  P.mix("wood4", "stone4", 0.5)],
        "rock": [P.c("stone0"), P.c("stone1"), P.c("stone2"), P.c("stone3")],
        "eyeglow": [P.c("red1"), P.c("red2"), P.c("red3"), P.c("red4")],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red1"), P.c("red2")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.mix("stone1", "ink2", 0.5), P.c("ink3")],
    },
    codes=_codes({"R": ("rock", 3), "S": ("rock", 2), "Q": ("rock", 1)}), leg_top=18,
    note="环形山的下阶妖兽：几丈高的巨型野猪，比野猪大一圈，背上石皮一块压一块、白獠牙上翘；出招是低头猛冲。",
)

# ===========================================================================
# 铁臂猿：弓背的灰褐大猿，两条前臂铁灰发亮、拳头拄地
# ===========================================================================

TIEBI_IDLE = tpl("""
................................
................................
................................
................................
................................
.................AAAA...........
...............AABBBBAA.........
..............ABBBBBBBBA........
..............ABBBBFFFFBA.......
.......AAAAAAABBBBFFeFFFBn......
.....AABBBBBBBBBBBBFFFFFrn......
....ABBBBBBBBBBBBBBBFFFFC.......
...ABBBBBBBBBBBBBBBBBCCC........
...ABBBBBBBBBBBBBBBBMMMM........
...ABBBBBBBBBBBBBBBMLLMMM.......
...ABBBBBFFFFFFBBBBBMMLMMM......
...CBBBBFFFFFFFFBBBBBMMLMMM.....
...CBBBBBFFFFFFBBBBBC.MMLMMM....
....CBBBBBBBBBBBBBBC...MMLMMM...
....CBBBBBBBBBBBBBBC....MMMMMM..
.....CBBBC....CBBBBC....MMMMMM..
.....CBBBC....CBBBC....MMLLMMMM.
.....CBBBC....CBBBC....MMMMMMMM.
.....CBBC.....CBBC.....NNMMMNN..
....DCBBC....DCBBC.....NN.N.NN..
....kkkkk....kkkkk..............
................................
................................
................................
................................
................................
................................
""")
TIEBI_ATTACK = tpl("""
......................MMMM......
.....................MMLLMM.....
.....................MLLMMM.....
....................MMLMMM......
...................MMLMMM.......
.................AAMLMMM........
...............AABBMMMA.........
..............ABBBBMMBBA........
..............ABBBBFFFFBA.......
.......AAAAAAABBBBFFeFFFBn......
.....AABBBBBBBBBBBBFFFFrrrn.....
....ABBBBBBBBBBBBBBBFFFFFC......
...ABBBBBBBBBBBBBBBBBCCC........
...ABBBBBBBBBBBBBBBBMMMM........
...ABBBBBBBBBBBBBBBMLLMMM.......
...ABBBBBFFFFFFBBBBBMMLMMM......
...CBBBBFFFFFFFFBBBBBMMLMMM.....
...CBBBBBFFFFFFBBBBBC.MMLMMM....
....CBBBBBBBBBBBBBBC...MMLMMM...
....CBBBBBBBBBBBBBBC....MMMMMM..
.....CBBBC....CBBBBC....MMMMMM..
.....CBBBC....CBBBC....MMLLMMMM.
.....CBBBC....CBBBC....MMMMMMMM.
.....CBBC.....CBBC.....NNMMMNN..
....DCBBC....DCBBC.....NN.N.NN..
....kkkkk....kkkkk..............
................................
................................
................................
................................
................................
................................
""")
TIEBI_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..........AAAAAAAAAAAA..........
.......AABBBBBBBBBBBBBBAAAA.....
.....AABBBBBBFFFFFFBBBBBFFFBA...
....ABBBBBBBFFFFFFFFBBBBFnFFBn..
...CBBBBBBBBBFFFFFFBBBBBFFFrC...
...CMMMMMMLLMMMMMBBBBBBBBCCC....
....NNMMMMMMMMMNNCCBBCCBBC......
.....kkkkkk..........kkkkk......
................................
................................
................................
................................
""")

TIEBI = Beast(
    id="tiebi_yuan", name="铁臂猿", w=32, h=32,
    idle=tuple(TIEBI_IDLE), attack=tuple(TIEBI_ATTACK), down=tuple(TIEBI_DOWN),
    ramps={
        "fur": [P.mix("soil0", "ink1", 0.5), P.mix("soil1", "stone1", 0.5), P.mix("soil2", "stone2", 0.5),
                P.mix("soil3", "stone3", 0.5)],
        "belly": [P.mix("skin0", "soil1", 0.5), P.mix("skin1", "soil2", 0.5), P.mix("skin2", "soil3", 0.4),
                  P.mix("skin3", "soil4", 0.4)],
        "metal": [P.mix("stone0", "water0", 0.3), P.mix("stone1", "water1", 0.3), P.mix("stone2", "water2", 0.3),
                  P.mix("stone4", "plaster3", 0.4)],
        "eyeglow": [P.c("red1"), P.c("red2"), P.c("red3"), P.c("red4")],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red1"), P.c("red2")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.mix("soil1", "ink2", 0.5), P.c("ink3")],
    },
    codes=_codes({"M": ("metal", 2), "L": ("metal", 3), "N": ("metal", 1)}), leg_top=20,
    note="环形山的下阶妖兽，两只一起出没：弓背的灰褐大猿，两条前臂铁灰发亮、拳头拄地；出招是抡起一臂往下砸。",
)

# ===========================================================================
# 火焰鼠：一级下阶的小兽，个头小，背上一溜火苗、尾尖一点火星
# ===========================================================================

HUOYAN_IDLE = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..........O.O...................
.........OYOYO..................
........OAAAAAO....AA...........
.......ABBBBBBBBAAABBA..........
......ABBBBBBBBBBBBBBBeBn.......
.O...ABBBBBBBBBBBBBBBBBBnn......
OYO.ABBBBFFFFFFFBBBBBCCC........
.OCCBBBBGGGGGGGGGBBBBC..........
....CCBC.CBC....CBC.CBC.........
.....kk...kk.....kk..kk.........
................................
................................
""")
HUOYAN_ATTACK = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........O.O..................
..........OYOYO.................
.........OAAAAAO.....AA.........
........ABBBBBBBBAAAABBA........
.......ABBBBBBBBBBBBBBBBeBn..Y..
.O....ABBBBBBBBBBBBBBBBBBrrO.YOY
OYO..ABBBBFFFFFFFBBBBBBCCrOYOYO.
.OCCCBBBBGGGGGGGGGBBBBC....OYO.Y
.....CCBC.CBC....CBC.CBC....O...
......kk...kk.....kk..kk........
................................
................................
................................
................................
""")
HUOYAN_DOWN = tpl("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.........ZZZZZZ.......AA........
.......ABBBBBBBBAAAAAABBA.......
.....ZABBBFFFFFFFBBBBBBBnBn.....
...ZZCCBGGGGGGGGGBBBBBBBBnn.....
......CkkCkkC...CkkCkkC.........
................................
................................
""")

HUOYAN = Beast(
    id="huoyan_shu", name="火焰鼠", w=32, h=24,
    idle=tuple(HUOYAN_IDLE), attack=tuple(HUOYAN_ATTACK), down=tuple(HUOYAN_DOWN),
    ramps={
        "fur": [P.mix("red0", "ink1", 0.4), P.c("red1"), P.mix("red2", "autumn1", 0.5), P.mix("red3", "autumn2", 0.5)],
        "belly": [P.mix("autumn1", "soil3", 0.5), P.mix("autumn2", "soil4", 0.5), P.mix("autumn3", "plaster1", 0.4),
                  P.mix("gold3", "plaster2", 0.4)],
        "flame": [P.c("red2"), P.c("red3"), P.c("gold2"), P.mix("gold4", "paper", 0.4)],
        "ash": [P.c("ink1"), P.c("ink2"), P.c("stone1"), P.c("stone2")],
        "eyeglow": [P.c("gold1"), P.c("gold2"), P.c("gold3"), P.mix("gold4", "paper", 0.3)],
        "tooth": [P.c("stone4"), P.c("plaster1"), P.c("plaster2"), P.c("plaster3")],
        "mouth": [P.c("red0"), P.c("red1"), P.c("red1"), P.c("red2")],
        "claw": [P.c("ink1"), P.c("ink2"), P.c("ink3"), P.c("ink4")],
        "ink": [P.c("ink0"), P.c("ink1"), P.c("ink1"), P.c("ink2")],
    },
    codes=_codes({"O": ("flame", 2), "Y": ("flame", 3), "Z": ("ash", 2)}), leg_top=19,
    note="环形山里一级下阶的小兽，成群出没：个头小，赤红的毛，背上一溜火苗、尾尖一点火星；出招是冲着人喷一口火星；倒下时火灭成灰。",
)


def _chapter8_rows(kind, pose, w=32, h=24):
    rows = [["."] * w for _ in range(h)]
    def dot(x, y, code="B"):
        if 0 <= x < w and 0 <= y < h:
            rows[y][x] = code
    def line(x0, y0, x1, y1, code="C"):
        n = max(abs(x1 - x0), abs(y1 - y0), 1)
        for step in range(n + 1):
            dot(round(x0 + (x1 - x0) * step / n), round(y0 + (y1 - y0) * step / n), code)
    def ellipse(cx, cy, rx, ry, code="B"):
        for y in range(max(0, cy - ry), min(h, cy + ry + 1)):
            for x in range(max(0, cx - rx), min(w, cx + rx + 1)):
                if ((x - cx) / max(rx, 1)) ** 2 + ((y - cy) / max(ry, 1)) ** 2 <= 1:
                    dot(x, y, "A" if y < cy - ry // 2 else code)
    down = pose == 2
    shift = 2 if pose == 1 else 0
    if kind == "xue_gui":
        ellipse(17 + shift, 9 if not down else 19, 7, 7 if not down else 2)
        if not down:
            for x in (12, 16, 21):
                line(x, 14, x - 3, 21)
            dot(19 + shift, 8, "e")
            dot(22 + shift, 8, "e")
            if pose == 1:
                line(22, 13, 30, 9, "A")
        else:
            for x in (8, 15, 24):
                dot(x, 18, "A")
    elif kind == "xue_zhizhu":
        ellipse(14 + shift, 11 if not down else 19, 8, 6 if not down else 2)
        ellipse(23 + shift, 12 if not down else 19, 4, 4 if not down else 2, "C")
        for x in (8, 13, 18, 22):
            if not down:
                line(x, 12, x - 5, 16)
                line(x - 5, 16, x - 6, 21)
                line(x, 12, x + 3, 5)
                line(x + 3, 5, x + 6, 3)
        dot(26 + shift, 11 if not down else 19, "e" if not down else "n")
        if pose == 1:
            line(27, 13, 31, 13, "W")
    elif kind == "kuilei_shou":
        for y in range(8 if not down else 17, 18 if not down else 21):
            for x in range(7, 25):
                dot(x, y, "A" if y % 4 == 0 else "C" if x % 5 == 0 else "B")
        if not down:
            for x in (9, 22):
                line(x, 17, x + shift, 21, "D")
            ellipse(25 + shift, 9, 4, 4)
            dot(28 + shift, 8, "e")
            if pose == 1:
                line(28, 11, 31, 11, "W")
    else:
        ellipse(15 + shift, 15 if not down else 20, 10, 4 if not down else 2)
        ellipse(25 + shift, 13 if not down else 19, 5, 4 if not down else 2)
        line(7, 16 if not down else 20, 1, 19, "C")
        if not down:
            for x in (11, 21):
                line(x, 17, x - shift, 21, "k")
            dot(28 + shift, 12, "e")
            if kind == "shuangtong_shu":
                ellipse(24 + shift, 8, 2, 3)
                ellipse(28 + shift, 8, 2, 3)
                dot(26 + shift, 12, "e")
            else:
                for x in (10, 14, 18):
                    line(x, 12, x, 10, "A")
            if pose == 1:
                dot(29, 15, "r")
                dot(30, 15, "W")
        else:
            dot(28, 19, "n")
    return tuple("".join(row) for row in rows)


def _chapter8_beast(kind, name, body):
    ramps = dict(WOLF.ramps)
    ramps["fur"] = [P.mix(body, "ink1", .6), P.mix(body, "ink3", .3),
                    P.c(body), P.mix(body, "paper", .25)]
    return Beast(kind, name, 32, 24, _chapter8_rows(kind, 0),
                 _chapter8_rows(kind, 1), _chapter8_rows(kind, 2),
                 ramps, _codes(), 19, "第8章非人形：独立剪影、出招与倒下帧。")


CHAPTER8_BEASTS = tuple(_chapter8_beast(*entry) for entry in (
    ("shuangtong_shu", "双瞳鼠", "soil4"),
    ("xue_gui", "血鬼", "red2"),
    ("xue_zhizhu", "血蜘蛛", "red3"),
    ("kuilei_shou", "傀儡兽", "stone3"),
    ("huangyuan_xiyi", "荒原蜥蜴", "jade2"),
))

BEASTS = (WOLF, CAGE, STIFF, SHIGUI, BOAR, BISHE, CHUANSHAN, MOJIAO, TUISHAN, TIEBI, HUOYAN) + CHAPTER8_BEASTS


def _canvas_from(rows: tuple[str, ...], beast: Beast) -> Canvas:
    c = Canvas(beast.w, beast.h)
    c.stamp(list(rows), 0, 0, beast.codes)
    return c


def _breath(c: Canvas, leg_top: int) -> Canvas:
    """待机第二帧：腿以上整体下沉一格（腿不动，身子压一压）。"""
    out = c.copy()
    for y in range(leg_top - 1, 0, -1):
        out.px[y] = c.px[y - 1][:]
    out.px[0] = [None] * c.w
    # 腿顶那一行保持原样，免得身子与腿之间裂开一道缝
    out.px[leg_top - 1] = [c.px[leg_top - 1][x] or c.px[leg_top - 2][x] for x in range(c.w)]
    return out


def _hurt(c: Canvas) -> Canvas:
    """受击：往后（左）一缩、往上一挺；眼睛闭上（眼光换成暗面）。"""
    out = c.shifted(-2, -1)
    for y in range(out.h):
        for x in range(out.w):
            v = out.px[y][x]
            if v is not None and v[0] == "eyeglow":
                out.px[y][x] = ("ink", 1)
    return out


def render_beast(beast: Beast) -> tuple[Image.Image, dict[str, list[int]]]:
    mats = Materials.build(beast.ramps)
    idle0 = _canvas_from(beast.idle, beast)
    frames = [
        idle0,
        _breath(idle0, beast.leg_top),
        _canvas_from(beast.attack, beast),
        _hurt(idle0),
        _canvas_from(beast.down, beast),
    ]
    imgs = [to_image(add_outline(f, mats), mats) for f in frames]
    layout = {"idle": [0, 1], "attack": [2], "hurt": [3], "down": [4]}
    return grid_sheet(imgs, len(imgs), beast.w, beast.h), layout


# ===========================================================================
# 元神光球（识海之战）
# ===========================================================================

def render_world_mouse() -> Image.Image:
    """The map mouse uses the standard 16x24, four-direction character format."""
    mouse = next(beast for beast in CHAPTER8_BEASTS if beast.id == "shuangtong_shu")
    battle, _ = render_beast(mouse)
    def side(index, left=False, step=0):
        src = battle.crop((index * mouse.w, 0, (index + 1) * mouse.w, mouse.h))
        src = src.resize((16, 12), Image.Resampling.NEAREST)
        out = Image.new("RGBA", (16, 24))
        out.alpha_composite(src, (0, 12))
        if step == 2:
            tail = out.crop((0, 18, 5, 23))
            out.paste((0, 0, 0, 0), (0, 18, 5, 23))
            out.alpha_composite(tail, (0, 17))
        if left:
            out = out.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
        return out
    mats = Materials.build(mouse.ramps)
    def end_view(back, step):
        rows = [["."] * 16 for _ in range(24)]
        def dot(x, y, code):
            if 0 <= x < 16 and 0 <= y < 24:
                rows[y][x] = code
        for y in range(13, 21):
            for x in range(3, 13):
                if ((x - 7.5) / 5) ** 2 + ((y - 17) / 4) ** 2 <= 1:
                    dot(x, y, "A" if y < 15 else "B")
        head_y = 12 if back else 18
        for y in range(head_y - 2, head_y + 3):
            for x in range(4, 12):
                if ((x - 7.5) / 4) ** 2 + ((y - head_y) / 3) ** 2 <= 1:
                    dot(x, y, "C" if back else "B")
        for x in (4, 11):
            dot(x, head_y - 3, "A")
            dot(x, head_y - 2, "B")
        if not back:
            for x in (5, 10):
                dot(x, head_y, "e")
            dot(7, head_y + 2, "n")
            for y in range(9, 14):
                dot(7 + y % 2, y, "C")
        else:
            for y in range(19, 22):
                dot(8 + y % 2, y, "C")
        for x in (4, 11):
            dot(x + (1 if step == 1 else -1 if step == 2 else 0), 21, "k")
        c = Canvas(16, 24)
        c.stamp(["".join(row) for row in rows], 0, 0, mouse.codes)
        return to_image(add_outline(c, mats), mats)
    frames = [end_view(False, step) for step in range(3)]
    frames += [side(i, True, step) for step, i in enumerate((0, 1, 0))]
    frames += [side(i, step=step) for step, i in enumerate((0, 1, 0))]
    frames += [end_view(True, step) for step in range(3)]
    frames += [side(i, True) for i in (0, 1, 1, 2, 2, 3, 4, 0, 1)]
    return grid_sheet(frames, 3, 16, 24)



@dataclass(frozen=True)
class Orb:
    id: str
    name: str
    size: int
    radius: float
    core: tuple[str, str, str, str]   # 由外到内四级色（主色板色名）
    wisp: str
    wisps: int
    phase: float
    note: str = ""


ORBS = (
    Orb("hanli_yuanshen", "韩立元神", 32, 7.5, ("jade1", "jade2", "jade3", "jade4"), "gold4", 3, 0.0,
        "韩立在识海里的元神：青玉色，芯子一点暖白。"),
    Orb("mo_juren_yuanshen", "墨居仁元神", 32, 9.0, ("ink4", "ink6", "stone5", "plaster3"), "jade3", 4, 1.3,
        "夺舍而来的墨居仁元神：灰白冷光，边上绕着几缕青气。"),
    Orb("yu_zitong", "余子童（元神）", 40, 12.5, ("violet0", "violet1", "violet2", "red3"), "red4", 5, 2.1,
        "「比韩立大了有一圈有余」：暗紫、芯子发红的一团，比韩立的光球大一圈半。"),
)


def _orb_frame(orb: Orb, t: int, mode: str) -> Image.Image:
    """画一帧光球。mode: idle（t=0..3 脉动）/ hurt（压扁、偏白）/ down（散成碎光）。

    全部按像素中心取样再量化到色阶，不用 PIL 的抗锯齿，保证每台机器同一结果。
    """
    s = orb.size
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    px = img.load()
    cx = cy = (s - 1) / 2.0
    pulse = [0.0, 0.6, 1.0, 0.6][t % 4]
    r0 = orb.radius * (1.0 + 0.10 * pulse)
    if mode == "hurt":
        r0 = orb.radius * 0.9
    ramp = [P.c(n) for n in orb.core]
    halo_c = P.c(orb.core[1])
    for y in range(s):
        for x in range(s):
            dx, dy = x - cx, y - cy
            if mode == "hurt":
                dx *= 0.85
                dy *= 1.25
            d = math.hypot(dx, dy)
            if mode == "down":
                # 散：外圈碎成点，芯子缩小变淡
                r_core = orb.radius * 0.45
                if d <= r_core:
                    k = d / r_core
                    col = ramp[3] if k < 0.4 else ramp[2]
                    px[x, y] = col + (200,)
                    continue
                ang = math.atan2(dy, dx)
                ring = orb.radius * 1.2
                if abs(d - ring) < 1.0 and (int((ang + math.pi) / (2 * math.pi) * 16) % 3 == 0):
                    px[x, y] = ramp[1] + (170,)
                continue
            if d <= r0:
                k = d / r0
                if k < 0.35:
                    col = ramp[3]
                elif k < 0.62:
                    col = ramp[2]
                elif k < 0.86:
                    col = ramp[1]
                else:
                    col = ramp[0]
                # 左上受光：芯子往左上偏一格的亮斑
                if math.hypot(dx + r0 * 0.35, dy + r0 * 0.35) < r0 * 0.22:
                    col = P.mix(ramp[3], "paper", 0.5)
                if mode == "hurt":
                    col = P.mix(col, "paper", 0.45)
                px[x, y] = col + (255,)
            elif d <= r0 + 3.0:
                # 光晕：三圈逐级变淡（半透明像素，运行时的辉光再把它晕开）
                band = int(d - r0)
                a = (150, 90, 40)[min(2, band)]
                a = int(a * (0.75 + 0.25 * pulse))
                px[x, y] = halo_c + (a,)
    if mode != "down":
        # 绕行的游丝：几个亮点沿椭圆轨道转，每帧转一格
        wc = P.c(orb.wisp)
        for i in range(orb.wisps):
            ang = orb.phase + i * (2 * math.pi / orb.wisps) + t * (math.pi / 8)
            rx, ry = r0 + 2.5, (r0 + 2.5) * 0.55
            wx = int(round(cx + rx * math.cos(ang)))
            wy = int(round(cy + ry * math.sin(ang)))
            for ddx, ddy, a in ((0, 0, 255), (1, 0, 140), (-1, 0, 140), (0, 1, 110), (0, -1, 110)):
                xx, yy = wx + ddx, wy + ddy
                if 0 <= xx < s and 0 <= yy < s:
                    old = px[xx, yy]
                    if old[3] < a:
                        px[xx, yy] = wc + (a,)
    return img


def render_orb(orb: Orb) -> tuple[Image.Image, dict[str, list[int]]]:
    frames = [_orb_frame(orb, t, "idle") for t in range(4)]
    frames.append(_orb_frame(orb, 0, "hurt"))
    frames.append(_orb_frame(orb, 0, "down"))
    layout = {"idle": [0, 1, 2, 3], "hurt": [4], "down": [5]}
    return grid_sheet(frames, len(frames), orb.size, orb.size), layout
