"""人物身体模板：长衣（长衫/道袍/襦裙/宽袍）与短衣（短打/短褐/皮甲/劲装）两个剪影族。

为什么只分两族：
  16×24 的人，区分「这是谁」靠的是剪影——下摆到脚还是露出两条腿，是剪影上最大的差别；
  同一族里长衫与襦裙、短打与皮甲的差别在颜色与局部（领口、甲片、敞怀），
  用「区域→材质」映射在上色时解决，不必各画一套。于是两族 × 每族 17 帧，就够全员用。

模板坐标：每张 16 宽 × 14 高，盖在帧的第 9–22 行（第 23 行留给脚底描边）。
行走帧前两行通常是空的；战斗帧可以把手举进这两行。
头部另画（sprites_head），按每帧的 head 偏移放在默认位置 (2, 1) 的基础上。

身体模板码表（区域 → 上色时再按衣型映射到具体材质）：
  A B C D  上身 torso      3/2/1/0 级
  I J K L  袖子 sleeve     3/2/1/0 级
  N O P R  下摆 lower      3/2/1/0 级（长衣的裙摆、短衣的衣摆）
  E F G H  裤腿 pants      3/2/1/0 级
  T t      领口/缘边 trim
  Y y      腰带 belt
  Q S s    皮肤（手、敞怀的胸口）
  M m      鞋
  W w      绑腿
  x z      可选「敞怀」：敞怀时是皮肤，否则是上身 B/C
  i j k    可选「宽袖」：宽袖时是袖子 3/2/1 级，否则透明
  1 2      近手 / 远手（皮肤，同时记下握持点）
"""

from __future__ import annotations

from dataclasses import dataclass

from sprites_core import tpl

BODY_ROWS = 14      # 模板 14 行，常人盖在帧的第 9–22 行；头框（12×10）默认左上角在 (2, 1)


@dataclass(frozen=True)
class BodyFrame:
    rows: tuple[str, ...]
    head: str = "F"            # 头朝向：F 正、L 左侧、B 背
    head_dx: int = 0
    head_dy: int = 0
    weapon: str = "none"       # 手持兵刃的姿态，见 sprites_props.WEAPON_STATES
    # 体型手术用：可删/可复制的行（模板行号）与列
    torso_row: int = 5
    leg_row: int = 10
    mid_col: int = 7


def F(text: str, **kw) -> BodyFrame:
    rows = tpl(text)
    assert len(rows) == BODY_ROWS, f"身体模板须 {BODY_ROWS} 行，实得 {len(rows)}"
    for r in rows:
        assert len(r) == 16, f"身体模板须 16 列：{r!r}"
    return BodyFrame(rows=tuple(rows), **kw)


# ===========================================================================
# 长衣族
# ===========================================================================

LONG: dict[str, BodyFrame] = {}

# ---- 行走：正面 ----
LONG["F0"] = F("""
................
................
....IBTSSTBK....
...IJBBTTBCKL...
...IJBBTBBCKL...
..iIJBTBBBCKLk..
..iJJTBBBBCKLk..
...1SYYYYYYs2...
....NOOOOOOP....
....NOOOOOOP....
...NOOOOOOPPR...
...NOOOOOOPPR...
...NOOOOOOPPR...
.....MM..mm.....
""", head="F")
LONG["F1"] = F("""
................
................
................
....IBTSSTBK....
...IJBBTTBCKL...
...IJBBTBBCK2...
..iIJBTBBBCKsk..
..iJJTBBBBCPRk..
...1SYYYYYYyP...
....NOOOOOOP....
...NOOOOOOPPR...
...NOOOOOOPPR...
...NNOOOOOPR....
....MMM.........
""", head="F", head_dy=1)
LONG["F2"] = F("""
................
................
................
....IBTSSTBK....
...IJBBTTBCKL...
...1JBBTBBCKL...
..iSJBTBBBCKLk..
..iNJTBBBBCKLk..
...NOYYYYYYs2...
....NOOOOOOP....
...NOOOOOOPPR...
...NOOOOOOPPR...
....NOOOOOPPR...
.........mmm....
""", head="F", head_dy=1)

# ---- 行走：侧面（朝左） ----
LONG["L0"] = F("""
................
................
.....TBBBCD.....
.....tBIJCCD....
.....BBIJCCD....
.....BBIJCCDk...
.....BBJJCCDk...
.....YY1SYyy....
.....NOOOOPR....
.....NOOOOPR....
....NOOOOOPR....
....NOOOOOPPR...
....NOOOOOPPR...
....MMM..mm.....
""", head="L", mid_col=8)
LONG["L1"] = F("""
................
................
................
.....TBBBCD.....
.....tBBIJCD....
.....BBBIJCDk...
.....BBBBJKDk...
.....BBBBCJ1....
.....YYYYyyS....
....NOOOOOPR....
...NOOOOOOPR....
..NOOOOOOOPPR...
..NOOO...OPPR...
..MMM.....mmm...
""", head="L", head_dy=1, mid_col=8)
LONG["L2"] = F("""
................
................
................
.....TBBBCD.....
.....tIJBCCD....
....iIJBBCCD....
....IJBBBCCD....
....1SBBBCCD....
.....YYYYyyy....
.....NOOOOPR....
....NOOOOOPPR...
...NOOOOOOPPR...
...NOOO..OPPR...
...MMm....mmm...
""", head="L", head_dy=1, mid_col=8)

# ---- 战斗（侧身朝左） ----
# 待机：前脚在左、后脚在右，重心压低；近手持兵刃在身前。
LONG["stance"] = F("""
................
................
................
......TBBBCD....
.....tBBBBCCD...
....1IJBBBCCD...
.....IJBBBCCD...
.....BBBBBCCD...
.....YYYYYyyy...
....NOOOOOOPR...
...NOOOOOOOPPR..
..NOOO...OOOPR..
..NOO.....OPPR..
.MMM.......mmm..
""", head="L", head_dx=1, head_dy=1, weapon="stance", mid_col=8)
# 蓄势：身子后仰，兵刃举到脑后；前脚点地。
LONG["ready"] = F("""
................
................
................
................
......TBBBCD....
.....tBBBBCCD...
....SBBBBBCCD...
.....BBBIJ1CD...
.....YYYYYyyy...
....NOOOOOOPR...
...NOOOOOOOPR...
..NOOO...OOPR...
..NOO.....OPR...
.MMM......mmm...
""", head="L", head_dx=0, head_dy=3, weapon="ready", mid_col=8)
# 出招：前冲，身子前倾，近手连兵刃往前递出；后腿蹬直。
LONG["attack"] = F("""
................
................
................
................
...TBBBBCD......
..1IJJBBBCD.....
....IJBBBCCD....
.....BBBBCCDD...
.....YYYYyyyD...
....NOOOOOPPPR..
...NOOOOOOOOPR..
..NOOO....OPPR..
.NOO.......PPR..
.MM.........mm..
""", head="L", head_dx=-2, head_dy=2, weapon="attack", mid_col=7)
# 施法：站直，近手并指在胸前（剑指），远手收在腰后；衣摆微扬。
LONG["cast"] = F("""
................
................
................
......TBBBCD....
.....tBBBBCCD...
...1IJJBBBCCD...
.....IJBBBCCDk..
.....BBBBBCCDk..
.....YYYYYyyy...
.....NOOOOOPR...
....NOOOOOOPPR..
....NOOOOOOPPR..
...NOOOO.OOPPR..
...MMM.....mmm..
""", head="L", head_dx=1, head_dy=1, weapon="cast", mid_col=8)
# 受击：上身后仰，头往后甩，前脚离地。
LONG["hurt"] = F("""
................
................
................
................
........TBCD....
.......tBBBCD...
......BBBBBCCD..
......BBBBBCCJ1.
.....BBBBBCCD...
.....YYYYYyyy...
....NOOOOOOPR...
...NOOOOOOOPR...
..NNOOO..OOPR...
.MM.......mmm...
""", head="L", head_dx=2, head_dy=3, weapon="hurt", mid_col=8)
# 倒地：单膝跪倒，一手撑地，头垂下。
LONG["down"] = F("""
................
................
................
................
................
................
......TBBBCD....
.....tBBBBCCD...
....IJBBBBCCD...
...IJ.BBBBCCD...
...J..YYYYyyy...
..1S.NOOOOOPR...
....NOOOOOOOPPR.
...MMOOOOOOOPPRm
""", head="L", head_dx=0, head_dy=6, weapon="down", mid_col=8, torso_row=8, leg_row=12)
# 胜利：抱拳。两手合在胸前，身子站直。
LONG["victory"] = F("""
................
................
................
......TBBBCD....
.....tBBBBCCD...
.....BIJBBCCD...
....1SSJBBCCD...
.....IJBBBCCD...
.....YYYYYyyy...
.....NOOOOOPR...
.....NOOOOOPR...
....NOOOOOOPPR..
....NOOOOOOPPR..
....MMM...mmm...
""", head="L", head_dx=1, head_dy=1, weapon="victory", mid_col=8)
# 防御：兵刃竖在身前，身子缩起。
LONG["guard"] = F("""
................
................
................
................
......TBBBCD....
.....tBBBBCCD...
....1IJBBBCCD...
....SIJBBBCCD...
.....BBBBBCCD...
.....YYYYYyyy...
....NOOOOOOPR...
...NOOOOOOOPPR..
..NOOO....OPPR..
..MMM......mmm..
""", head="L", head_dx=1, head_dy=2, weapon="guard", mid_col=8)


# ===========================================================================
# 短衣族
# ===========================================================================

SHORT: dict[str, BodyFrame] = {}

SHORT["F0"] = F("""
................
................
....IBTSSTBK....
...IJBBTTBCKL...
...IJBBTBBCKL...
...IJBTBBBCKL...
...JJTBBBBCKL...
...1SYYYYYYs2...
....NOOOOOOP....
....EFFFFGGG....
....EFF..FGG....
.....FG..FG.....
.....Ww..Ww.....
....MMm..MMm....
""", head="F")
SHORT["F1"] = F("""
................
................
................
....IBTSSTBK....
...IJBBTTBCKL...
...IJBBTBBCK2...
...IJBTBBBCKs...
...JJTBBBBCCD...
...1SYYYYYYyD...
....NOOOOOOP....
....EFFFFGGG....
....FFG..FGG....
....WWw..mmm....
...MMMm.........
""", head="F", head_dy=1)
SHORT["F2"] = F("""
................
................
................
....IBTSSTBK....
...IJBBTTBCKL...
...1JBBTBBCKL...
...SJBTBBBCKL...
...ABTBBBBCKL...
...AYYYYYYYs2...
....NOOOOOOP....
....EFFFFGGG....
....EFF..GGG....
....mmm..WWw....
.........MMMm...
""", head="F", head_dy=1)
SHORT["L0"] = F("""
................
................
.....TBBBCD.....
.....tBIJCCD....
.....xBIJCCD....
.....zBIJCCDk...
.....BBJJCCDk...
.....YY1SYyy....
.....NOOOOPR....
.....EFFFGG.....
.....EFFGGG.....
.....EFGGG......
.....WWww.......
....MMMmm.......
""", head="L", mid_col=8)
SHORT["L1"] = F("""
................
................
................
.....TBBBCD.....
.....tBBIJCD....
.....xBBIJCDk...
.....zBBBJKDk...
.....BBBBCJ1....
.....YYYYyyS....
.....NOOOOPR....
....EFFFFGGG....
...EFF....GGG...
..WWw......Gww..
.MMM........mmm.
""", head="L", head_dy=1, mid_col=8)
SHORT["L2"] = F("""
................
................
................
.....TBBBCD.....
.....tIJBCCD....
....ixJBBCCD....
....IJBBBCCD....
....1SBBBCCD....
.....YYYYyyy....
.....NOOOOPR....
....EFFFFGGG....
....EFF..GGG....
...WWw....Gww...
..MMM......mmm..
""", head="L", head_dy=1, mid_col=8)

SHORT["stance"] = F("""
................
................
................
......TBBBCD....
.....txBBBCCD...
....1IJBBBCCD...
.....IJBBBCCD...
.....zBBBBCCD...
.....YYYYYyyy...
.....NOOOOOPR...
....EFFFFFGGG...
...EFF....GGG...
..WWw......Gww..
.MMM.......mmm..
""", head="L", head_dx=1, head_dy=1, weapon="stance", mid_col=8)
SHORT["ready"] = F("""
................
................
................
................
......TBBBCD....
.....txBBBCCD...
....SzBBBBCCD...
.....BBBIJ1CD...
.....YYYYYyyy...
.....NOOOOOPR...
....EFFFFFFGG...
..EFF.....GGG...
.WWw.......Gw...
.MM........mm...
""", head="L", head_dx=0, head_dy=3, weapon="ready", mid_col=8)
SHORT["attack"] = F("""
................
................
................
................
...TBBBBCD......
..1IJJxBBCD.....
....IJzBBCCD....
.....BBBBCCDD...
.....YYYYyyyD...
.....NOOOOOPPR..
....EFFFFFFGGG..
..EFF......GGG..
.WWw........Gw..
.MM.........mm..
""", head="L", head_dx=-2, head_dy=2, weapon="attack", mid_col=7)
SHORT["cast"] = F("""
................
................
................
......TBBBCD....
.....txBBBCCD...
...1IJJBBBCCD...
.....IJBBBCCDk..
.....zBBBBCCDk..
.....YYYYYyyy...
.....NOOOOOPR...
.....EFFFFGGG...
....EFF...GGG...
...WWw.....Gww..
...MMM.....mmm..
""", head="L", head_dx=1, head_dy=1, weapon="cast", mid_col=8)
SHORT["hurt"] = F("""
................
................
................
................
........TBCD....
.......txBBCD...
......zBBBBCCD..
......BBBBBCCJ1.
.....BBBBBCCD...
.....YYYYYyyy...
.....NOOOOOPR...
....EFFFFFGGG...
..EFF.....GGG...
.MM........mmm..
""", head="L", head_dx=2, head_dy=3, weapon="hurt", mid_col=8)
SHORT["down"] = F("""
................
................
................
................
................
................
......TBBBCD....
.....txBBBCCD...
....IJzBBBCCD...
...IJ.BBBBCCD...
...J..YYYYyyy...
..1S..NOOOOPR...
....EFFFFFFGGGG.
...MMFFFFFFFGGGm
""", head="L", head_dx=0, head_dy=6, weapon="down", mid_col=8, torso_row=8, leg_row=12)
SHORT["victory"] = F("""
................
................
................
......TBBBCD....
.....txBBBCCD...
.....zIJBBCCD...
....1SSJBBCCD...
.....IJBBBCCD...
.....YYYYYyyy...
.....NOOOOOPR...
.....EFFFFGG....
.....EFF.GGG....
.....WWw.Gww....
....MMM..mmm....
""", head="L", head_dx=1, head_dy=1, weapon="victory", mid_col=8)
SHORT["guard"] = F("""
................
................
................
................
......TBBBCD....
.....txBBBCCD...
....1IJBBBCCD...
....SIJBBBCCD...
.....zBBBBCCD...
.....YYYYYyyy...
.....NOOOOOPR...
....EFFFFFGGG...
...WWw.....Gww..
..MMM......mmm..
""", head="L", head_dx=1, head_dy=2, weapon="guard", mid_col=8)

FAMILIES: dict[str, dict[str, BodyFrame]] = {"long": LONG, "short": SHORT}


# ===========================================================================
# 体型手术：删行/复制行、删列/复制列
# ===========================================================================

def _dup_col(rows: list[str], col: int, times: int = 1) -> list[str]:
    return [r[:col] + r[col] * times + r[col:] for r in rows]


def _del_col(rows: list[str], col: int) -> list[str]:
    return [r[:col] + r[col + 1:] for r in rows]


def _dup_row(rows: list[str], row: int, times: int = 1) -> list[str]:
    return rows[:row] + [rows[row]] * times + rows[row:]


def _del_row(rows: list[str], row: int) -> list[str]:
    return rows[:row] + rows[row + 1:]


def _content_span(rows: list[str]) -> tuple[int, int] | None:
    cols = [i for r in rows for i, ch in enumerate(r) if ch != "."]
    if not cols:
        return None
    return min(cols), max(cols)


def _fit_width(rows: list[str], width: int, center_hint: float) -> tuple[list[str], int]:
    """把行宽裁/补到 width。返回 (新行, 左侧补了几列（负数为裁掉几列）)。

    按「实际有像素的范围」来裁：优先让 center_hint 这条中线落在新帧中线上，
    若那样会裁到像素，就往有空的一侧挪。实在比帧还宽就报错——那是模板或手术参数出了错，
    悄悄裁掉一只脚比报错更糟。
    """
    cur = len(rows[0])
    span = _content_span(rows)
    want_pad = int(round((width / 2.0 - 0.5) - center_hint))
    if span is None:
        pad = want_pad
    else:
        lo, hi = span
        if hi - lo + 1 > width:
            raise ValueError("体型手术把身体撑出了帧宽")
        # 需满足 lo+pad >= 0 且 hi+pad <= width-1
        pad = max(-lo, min(width - 1 - hi, want_pad))
    out = []
    for r in rows:
        if pad >= 0:
            r2 = "." * pad + r
        else:
            r2 = r[-pad:]
        r2 = r2[:width].ljust(width, ".")
        out.append(r2)
    return out, pad


def _pick(order: list[int], n: int, limit: int, what: str) -> list[int]:
    """从候选行/列里挑 n 个。挑不够就报错——宁可生成失败，也不悄悄少做几刀，
    让外观表里写的身高、体型与画出来的对不上。"""
    out: list[int] = []
    for c in order:
        if len(out) >= n:
            break
        if 0 <= c < limit and c not in out:
            out.append(c)
    if len(out) < n:
        raise ValueError(f"体型手术：{what}要动 {n} 处，模板里只有 {len(out)} 处能动")
    return out


def surgery(frame: BodyFrame, rows: list[str], widen: int, torso_rows: int, leg_rows: int,
            frame_w: int) -> tuple[list[str], float]:
    """体型手术。返回 (身体行, 人物中线在新帧里的 x)。

    插入点分散开（上身两侧各一列、两臂各一列……），而不是在中线上连插四列——
    连插会在身子正中留下一条毫无明暗变化的宽带，巨汉就成了一块门板。
    行的增删同理分散在上身、下身的几行里。
    中线跟踪：模板里人物中线在 x=7.5；中线左侧每插一列中线右移一格，删一列左移一格。
    """
    front = frame.head == "F"
    m = frame.mid_col
    width = len(rows[0])
    shift = 0
    if not front and frame_w <= 16:
        # 侧身只加宽两列：胖与壮在侧面差的是肚子，不是再宽一格；再宽，出招时前后脚就出帧了
        widen = min(widen, 2)
    if widen > 0:
        order = [5, 10, 4, 11, 7, 8] if front else [m - 1, m + 1, m - 2, m + 2, m]
        for c in sorted(_pick(order, widen, width, "加宽"), reverse=True):
            rows = _dup_col(rows, c)
            if c <= 7:
                shift += 1
    elif widen < 0:
        order = [10, 5, 9] if front else [m + 1, m - 1, m + 2]
        for c in sorted(_pick(order, -widen, width, "收窄"), reverse=True):
            rows = _del_col(rows, c)
            if c <= 7:
                shift -= 1
    t, l = frame.torso_row, frame.leg_row
    # 先动下身（行号大），再动上身，免得行号错位
    for what, n, dup_order, del_order in (
        ("下身", leg_rows, [l, l - 1, l + 1, l - 2], [l, l - 1, l + 1]),
        ("上身", torso_rows, [t, t - 1, t + 1], [t, t - 1, t + 1]),
    ):
        if n > 0:
            for r in sorted(_pick(dup_order, n, len(rows), what + "加高"), reverse=True):
                rows = _dup_row(rows, r)
        elif n < 0:
            for r in sorted(_pick(del_order, -n, len(rows), what + "缩短"), reverse=True):
                rows = _del_row(rows, r)
    rows, pad_l = _fit_width(rows, frame_w, 7.5 + shift)
    return rows, 7.5 + shift + pad_l
