"""地图物件精灵：设施（map_spec 4.6 的九种 kind）、传送点标记、交互闪光、NPC 头顶气泡。

全部拼进一张 objects.png，以 16px 为一格；一件物件可占多格、可有多帧。
帧表写进 index.json 的 objects 段：每件给出每帧的像素矩形与锚点（落地点：帧内最低一行
不透明像素的下沿，自动算；运行时把它对到对象所在格的底边中点，气泡则对到 NPC 头顶）。

画法与人物一致：字符模板 + 材质色阶 + 自动描边。发光的部分（丹炉火、阵盘、
传送光、闪光、气泡）另在 emissive 图层里给出（同尺寸、同位置，只含发光像素），
运行时把它画进辉光目标——HD-2D 的「亮」是后加的。
"""

from __future__ import annotations

from dataclasses import dataclass

from PIL import Image

import palette as P
from sprites_core import Canvas, Materials, add_outline, cloth_ramp, to_image, tpl

CELL = 16


def _ramp(*names: str) -> list[tuple[int, int, int]]:
    return [P.c(n) for n in names]


RAMPS = {
    # 金褐的铜（带一点铜绿）：放在草地上不能是一口绿锅
    "bronze": [P.mix("gold0", "ink1", 0.4), P.mix("gold0", "jade0", 0.25), P.mix("gold1", "wood2", 0.35), P.mix("gold2", "jade3", 0.15)],
    "gold": _ramp("gold0", "gold1", "gold2", "gold3"),
    "fire": [P.c("red1"), P.c("red3"), P.c("gold3"), P.c("gold4")],
    "wood": _ramp("wood1", "wood2", "wood3", "wood4"),
    "darkwood": _ramp("wood0", "wood1", "wood2", "wood3"),
    "stone": _ramp("stone1", "stone2", "stone3", "stone4"),
    "brick": [P.mix("red0", "stone0", 0.5), P.mix("red1", "stone1", 0.55), P.mix("red2", "stone2", 0.6), P.mix("red3", "stone3", 0.6)],
    "paper": _ramp("stone4", "stone5", "plaster2", "paper"),
    "talisman": [P.mix("gold1", "soil3", 0.3), P.c("gold2"), P.mix("gold3", "paper", 0.2), P.c("gold4")],
    "ink": _ramp("ink0", "ink1", "ink2", "ink3"),
    "cinnabar": _ramp("red1", "red2", "red3", "red4"),
    "jade": _ramp("jade0", "jade1", "jade3", "jade4"),
    "straw": _ramp("wood2", "wood3", "wood4", "wood5"),
    "straw_dk": _ramp("wood1", "wood2", "wood2", "wood3"),
    "cloth": cloth_ramp(P.mix("water1", "ink3", 0.45)),
    "cloth2": cloth_ramp(P.mix("red2", "soil2", 0.35)),
    "smoke": _ramp("stone3", "stone4", "stone5", "plaster3"),
    "glow": [P.mix("gold2", "paper", 0.2), P.mix("gold3", "paper", 0.3), P.mix("gold4", "paper", 0.4), P.c("paper")],
    "white": _ramp("stone4", "plaster2", "plaster3", "paper"),
    "leaf": _ramp("leaf2", "leaf3", "leaf5", "leaf6"),
}
MATS = Materials.build(RAMPS)

def codes(main: str, sub: str = "wood", **extra: tuple[str, int]) -> dict[str, tuple[str, int] | None]:
    d: dict[str, tuple[str, int] | None] = {
        "A": (main, 3), "B": (main, 2), "C": (main, 1), "D": (main, 0),
        "E": (sub, 3), "F": (sub, 2), "G": (sub, 1), "H": (sub, 0),
        "Z": ("gold", 3), "z": ("gold", 1),
        "f": ("fire", 1), "r": ("fire", 2), "y": ("fire", 3), "w": ("fire", 3),
        "k": ("ink", 1), "p": ("paper", 2), "q": ("paper", 3),
        "t": ("talisman", 2), "c": ("cinnabar", 2), "j": ("jade", 2), "J": ("jade", 3),
        "s": ("smoke", 2), "S": ("smoke", 3), "l": ("leaf", 2),
    }
    d.update(extra)
    return d


# 发光像素：画进 emissive 层的材质
EMISSIVE = {"fire", "glow", "jade"}


@dataclass(frozen=True)
class Obj:
    id: str
    name: str
    w: int          # 像素
    h: int
    frames: tuple[tuple[str, ...], ...]
    codes: dict
    fps: float = 0.0
    outline: bool = True
    note: str = ""
    ground_marker: bool = False   # 平铺在格子上的标记（箭头、闪光）：一帧就是一格，锚点取帧底边中点


def F(text: str) -> tuple[str, ...]:
    return tuple(tpl(text))


def pad_top(rows: tuple[str, ...], n: int) -> tuple[str, ...]:
    """在模板上面补 n 行空：物件帧高一律取 16 的倍数（施工要求「以 16px 格为单位」），落地点不变。"""
    w = len(rows[0])
    return tuple(["." * w] * n) + rows


# ===========================================================================
# 设施
# ===========================================================================

_CAULDRON_BODY = """
................................
................................
...............AB...............
.........ABC..ABBC..ABC.........
.........A.C.ABBBBC.A.C.........
.........ABCABBBBBBCABC.........
........ZZZZZZZZZZZZZZZZZ.......
.........ABBBBBBBBBBBBBCD.......
........ABBBBBBBBBBBBBBBCD......
.......ABBBBBBBZZZZBBBBBBCD.....
.......ABBBBBBZBBBBZBBBBBCD.....
.......ABBBBBBBZZZZBBBBBBCD.....
.......ABBBBBBBBBBBBBBBBBCD.....
........ABBBBBBBBBBBBBBBCD......
.........CBBBBBBBBBBBBBCD.......
..........CCBBBBBBBBBCCD........
..........DC{F1}DC........
..........DC{F2}DC........
.........DDC{F3}CDD.......
................................
................................
................................
................................
................................
"""
_FIRE = [
    ("..r..y..", ".rry.ry.", "rryyyyrr"),
    ("..y..r..", ".ryr.yr.", "rryyyyrr"),
    (".r...ry.", ".ryrryr.", "rryyyyrr"),
]


def _cauldron_frames() -> tuple[tuple[str, ...], ...]:
    out = []
    for a, b, c in _FIRE:
        text = _CAULDRON_BODY.replace("{F1}", a).replace("{F2}", b).replace("{F3}", c)
        out.append(pad_top(F(text), 8))
    return tuple(out)


ALCHEMY = Obj("facility.alchemy", "丹炉", 32, 32, _cauldron_frames(), codes("bronze"), fps=8.0,
              note="铜鼎：沿上一对立耳、隆起的鼎盖与钮、腹上一圈金纹、三足，足间炉火三帧跳动。")

_FORGE = """
................................
..............BBBC..............
..............ABCD..............
..............ABCD..............
...........AAAABBBCCC...........
.........AABBBBBBBBBBCC.........
........ABBBBBBBBBBBBBBC........
........ABBBBBBBBBBBBBBC........
........ABBBDDDDDDDDBBBC........
........ABBD{F1}DBBC........
........ABBD{F2}DBBC........
........ABBD{F3}DBBC........
........ABBBBBBBBBBBBBBC........
.......AABBBBBBBBBBBBBBCC.......
.......DDDDDDDDDDDDDDDDDD.......
................................
"""
_FORGE_FIRE = [("...r..y.", "..ryryr.", ".ryyyyr."), ("...y.r..", "..yrryr.", ".ryyyyr."), ("..r..y..", ".ryryr..", ".ryyyyr.")]


def _forge_frames() -> tuple[tuple[str, ...], ...]:
    out = []
    for a, b, c in _FORGE_FIRE:
        out.append(F(_FORGE.replace("{F1}", a).replace("{F2}", b).replace("{F3}", c)))
    return tuple(out)


FORGE = Obj("facility.forge", "器炉", 32, 16, _forge_frames(), codes("brick"), fps=8.0,
            note="砖砌地火炉：烟囱、炉口一膛火。")

TALISMAN = Obj("facility.talisman", "符案", 32, 16, (F("""
................................
.........tttt....k..............
........tcctt...kk..pppp........
.......ABBBBBBBBBBBBBBBBBBBBC...
......ABBBBBBBBBBBBBBBBBBBBBBC..
......CCCCCCCCCCCCCCCCCCCCCCCD..
.......CD..................CD...
.......CD..................CD...
.......CD..................CD...
.......DD..................DD...
................................
................................
................................
................................
................................
................................
"""),), codes("darkwood"),
    note="矮脚长案：一叠黄符（上有朱砂）、笔架、镇纸。")

FORMATION = Obj("facility.formation", "阵盘", 32, 16, tuple(F(t) for t in (
"""
................................
................................
.........AAAAAAAAAAAAAA.........
......AABBBBBBjBBBBBBBBBCC......
....ABBBBjjBBBBBBBBjjBBBBBCC....
...ABBBBBBBBBBJJBBBBBBBBBBBBC...
...ABBjBBBBBBJBBJBBBBBBBjBBBC...
...ABBBBBBBBBBJJBBBBBBBBBBBBC...
....CBBBBjjBBBBBBBBjjBBBBBCD....
......CCBBBBBBjBBBBBBBBBCD......
.........CCCCCCCCCCCCCCD........
................................
""",
"""
................................
................................
.........AAAAAAAAAAAAAA.........
......AABBBBBBJBBBBBBBBBCC......
....ABBBBJJBBBBBBBBJJBBBBBCC....
...ABBBBBBBBBBJJBBBBBBBBBBBBC...
...ABBJBBBBBBJBBJBBBBBBBJBBBC...
...ABBBBBBBBBBJJBBBBBBBBBBBBC...
....CBBBBJJBBBBBBBBJJBBBBBCD....
......CCBBBBBBJBBBBBBBBBCD......
.........CCCCCCCCCCCCCCD........
................................
""",
"""
................................
................................
.........AAAAAAAAAAAAAA.........
......AABBBBBBjBBBBBBBBBCC......
....ABBBBjJBBBBBBBBJjBBBBBCC....
...ABBBBBBBBBBjjBBBBBBBBBBBBC...
...ABBJBBBBBBjBBjBBBBBBBJBBBC...
...ABBBBBBBBBBjjBBBBBBBBBBBBC...
....CBBBBJjBBBBBBBBjJBBBBBCD....
......CCBBBBBBjBBBBBBBBBCD......
.........CCCCCCCCCCCCCCD........
................................
""")), codes("stone"), fps=4.0,
    note="平放在地上的石阵盘：刻着八个方位的纹路，纹路里的青光三帧流转。")

FIELD = Obj("facility.field", "灵田木牌", 16, 32, (F("""
................
................
................
................
................
................
................
................
................
................
................
................
...ABBBBBBBBC...
...ABppppppBC...
...ABpkkpkpBC...
...ABppppppBC...
...ABpkpkkpBC...
...ABppppppBC...
...CCCCCCCCCD...
.......BC.......
.......BC.......
.......BC.......
.......BC.......
.......BC.......
......lBCl......
.....llDDll.....
................
................
................
................
................
................
"""),), codes("wood"),
    note="田头插的木牌，贴一张写着字的纸，脚下一丛草。")

MEDITATE = Obj("facility.meditate", "蒲团", 16, 16, (F("""
................
................
................
................
................
................
................
....AAAAAAAA....
..AABBBBBBBBCC..
.ABBEEEEEEEEBBC.
.ABEBBBBBBBBECC.
.ABBEEEEEEEECCC.
..CCBBBBBBBCCD..
....DDDDDDDD....
................
................
"""),), codes("straw", "straw_dk"),
    note="草编圆蒲团：扁、厚边，一圈圈编纹。")
SHOP = Obj("facility.shop", "货摊", 32, 32, (F("""
................................
................................
................................
....AAAAAAAAAAAAAAAAAAAAAAA.....
...ABBEBBEBBEBBEBBEBBEBBEBBC....
..ABBBEBBBEBBBEBBBEBBBEBBBBBC...
..CCDCCDCCDCCDCCDCCDCCDCCDCCD...
...G.C..................C.G.....
...G.C..................C.G.....
...G.C..................C.G.....
...G.C..................C.G.....
...G.C..................C.G.....
...G.C..................C.G.....
...G.C..rr....jj..qq....C.G.....
...G.C.rffr..jJjj.pqq...C.G.....
...G.CwwwwwwwwwwwwwwwwwwC.G.....
...G.EFFFFFFFFFFFFFFFFFFG.G.....
...G.EFFFFFFFFFFFFFFFFFFG.G.....
...G.EFFGGGGGGGGGGGGGGFFG.G.....
...G.EFFFFFFFFFFFFFFFFFFG.G.....
...G.EFFFFFFFFFFFFFFFFFFG.G.....
...G.GGGGGGGGGGGGGGGGGGGG.G.....
...H.H..................H.H.....
................................
................................
................................
................................
................................
................................
................................
................................
................................
"""),), codes("cloth", "wood", w=("paper", 2), r=("cinnabar", 2), f=("cinnabar", 1)),
    note="布篷货摊：条纹布篷、柜台上摆着药罐、玉件与纸包。")

BOARD = Obj("facility.board", "告示板", 32, 32, (F("""
................................
................................
................................
................................
.....ABBBBBBBBBBBBBBBBBBBBBC....
....ABBBBBBBBBBBBBBBBBBBBBBBC...
....CCCCCCCCCCCCCCCCCCCCCCCD....
.....EFFFFFFFFFFFFFFFFFFFFG.....
.....EFqqqqqFFqqqqFFFqqqqqG.....
.....EFqkpkpFFqpkpFFFqkkpqG.....
.....EFqpppqFFqkppFFFqpppqG.....
.....EFqkkpqFFqpppFFFqkpkqG.....
.....EFqpppqFFqqqqFFFqpppqG.....
.....EFqqqqqFFFFFFFFFqqqqqG.....
.....EFFFFFFFFFFFFFFFFFFFFG.....
.....GGGGGGGGGGGGGGGGGGGGGG.....
......BC..............BC........
......BC..............BC........
......BC..............BC........
......BC..............BC........
......BC..............BC........
......BC..............BC........
.....DDDD............DDDD.......
................................
................................
................................
................................
................................
................................
................................
................................
................................
"""),), codes("darkwood", "wood"),
    note="带檐的木告示板，钉着几张写了字的纸。")

_BURNER = """
................................
{S1}
{S2}
{S3}
{S4}
{S5}
..............Z..Z..............
.............ZZZZZZ.............
..........AAABBBBBBCC...........
........AABBBBBBBBBBBCC.........
.......ABBBBBBBBBBBBBBBC........
.......ZZZZZZZZZZZZZZZZZ........
.....AB.ABBBBBBBBBBBBBC..CD.....
.....AB.ABBBBBBBBBBBBBC..CD.....
.......ABBBBBBZZZBBBBBBC........
.......ABBBBBZBBBZBBBBBC........
.......ABBBBBBZZZBBBBBBC........
........CBBBBBBBBBBBBBC.........
.........CCBBBBBBBBBCCD.........
..........DC...DC...DC..........
.........DDC..DDC..DDC..........
.......EEEEEEEEEEEEEEEEE........
......EFFFFFFFFFFFFFFFFFG.......
......GGGGGGGGGGGGGGGGGGG.......
"""
_SMOKE = [
    ["...............sS.............", "..............S...s...........", "...............s..S...........", "................sS.S..........", "................s.............."],
    ["................Ss............", "...............s..S...........", "..............S..s............", "...............sS.............", "................s.............."],
    ["...............S.s............", "................s.S...........", "...............S.s............", "..............sS..............", "................s.............."],
]


def _burner_frames() -> tuple[tuple[str, ...], ...]:
    out = []
    for sm in _SMOKE:
        t = _BURNER
        for i, line in enumerate(sm):
            t = t.replace("{S%d}" % (i + 1), line.ljust(32, "."))
        out.append(pad_top(F(t), 8))
    return tuple(out)


SAVE = Obj("facility.save", "香炉（存档）", 32, 32, _burner_frames(), codes("bronze", "stone"), fps=4.0,
           note="石台上一只铜香炉，三缕青烟三帧飘动。存档点。")


# ===========================================================================
# 传送点标记：地面发光的方向箭头 ×4 方向 ×3 帧；门光 ×3 帧
# ===========================================================================

def _arrow_rows(phase: int) -> list[str]:
    """朝上的箭头（地面上压扁的 V 字 ×2），phase 0-2 往前挪一格。"""
    base = [
        "................",
        "................",
        ".......AA.......",
        "......ABBA......",
        ".....AB..BA.....",
        "....AB....BA....",
        "...AB......BA...",
        "................",
        ".......AA.......",
        "......ABBA......",
        ".....AB..BA.....",
        "....AB....BA....",
        "...AB......BA...",
        "................",
        "................",
        "................",
    ]
    rows = ["." * 16] * (2 - phase) + base
    rows = rows[: 16] if len(rows) >= 16 else rows + ["." * 16] * (16 - len(rows))
    return rows


def _rotate(rows: list[str], d: str) -> list[str]:
    n = len(rows)
    if d == "up":
        return rows
    if d == "down":
        return [r for r in reversed(rows)]
    if d == "left":
        return ["".join(rows[y][n - 1 - x] for y in range(n)) for x in range(n)]
    if d == "right":
        return ["".join(rows[n - 1 - y][x] for y in range(n)) for x in range(n)]
    raise ValueError(d)


ARROWS = [
    Obj(f"portal.arrow_{d}", f"传送箭头（{d}）", 16, 16,
        tuple(tuple(_rotate(_arrow_rows(p), d)) for p in range(3)),
        {"A": ("glow", 3), "B": ("glow", 2)}, fps=6.0, outline=False, ground_marker=True,
        note="地面发光的方向箭头，三帧往前走；运行时加色混合。")
    for d in ("down", "left", "right", "up")
]

def _doorlight(rows: tuple[str, ...]) -> Image.Image:
    """门光：门洞里自下而上渐淡的一道光，两侧门框线更亮，几点光尘往上飘。

    rows 里只放帧号（'0'/'1'/'2'），图形由解析式算——渐变用字符模板画不细。
    """
    from fx_textures import hash01, smoothstep

    f = int(rows[0])
    w, h = 16, 32
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = img.load()
    col = P.mix("gold4", "paper", 0.5)
    pulse = (1.0, 0.82, 0.92)[f]
    for y in range(h):
        for x in range(w):
            if not (4 <= x <= 11) or y < 3 or y > 27:
                continue
            t = (27.5 - (y + 0.5)) / 24.0            # 0 在门槛 → 1 在门楣
            a = 200.0 * (1.0 - smoothstep(0.0, 1.0, t)) * pulse
            if x in (4, 11):
                a = min(255.0, a * 1.25 + 30.0)
            if y == 27:
                a = 255.0 * pulse
            a = int(round(a / 32.0)) * 32            # 量化成几级，保持像素画的硬
            if a > 0:
                px[x, y] = col + (min(255, a),)
    for i in range(4):
        mx = 5 + int(hash01(i, 0, 61) * 6)
        my = 26 - ((int(hash01(i, 1, 61) * 20) + f * 5) % 22)
        if 3 <= my <= 27:
            px[mx, my] = P.c("paper") + (255,)
    return img


DOORLIGHT = Obj("portal.door", "门光", 16, 32, (("0",), ("1",), ("2",)), {}, fps=4.0, outline=False,
                note="门洞里自下而上渐淡的一道光、门框线、往上飘的光尘，三帧明灭。运行时加色混合。")

PROCEDURAL = {"portal.door": _doorlight}

# ===========================================================================
# 交互闪光（4 帧）与头顶气泡
# ===========================================================================

_SPARK = [
"""
................
................
................
................
................
................
.......A........
......ABA.......
.......A........
................
................
................
................
................
................
................
""",
"""
................
................
................
................
.......A........
.......B........
.......B........
....ABBSBBA.....
.......B........
.......B........
.......A........
................
................
................
................
................
""",
"""
................
................
.......A........
.......B........
.......B........
.....B.B.B......
......BBB.......
..ABBBBSBBBBA...
......BBB.......
.....B.B.B......
.......B........
.......B........
.......A........
................
................
................
""",
"""
................
................
................
................
.......A........
................
.....A...A......
....A..S..A.....
.....A...A......
................
.......A........
................
................
................
................
................
""",
]
SPARKLE = Obj("mark.sparkle", "交互闪光", 16, 16, tuple(F(t) for t in _SPARK),
              {"A": ("glow", 1), "B": ("glow", 2), "S": ("glow", 3)}, fps=8.0, outline=False,
              ground_marker=True,
              note="可交互处地上的一点闪光，四帧由小到大再散开。")

_BUBBLE = """
................
..AAAAAAAAAAA...
.ABBBBBBBBBBBA..
.ABBBBBBBBBBBA..
.ABBBBBBBBBBBA..
.ABBBBBBBBBBBA..
.ABBBBBBBBBBBA..
.ABBBBBBBBBBBA..
.ABBBBBBBBBBBA..
..AAAABBAAAAA...
......BA........
......A.........
................
................
................
................
"""


def _bubble(glyph: list[str], ox: int = 3, oy: int = 2) -> tuple[str, ...]:
    rows = [list(r) for r in tpl(_BUBBLE)]
    for j, line in enumerate(glyph):
        for i, ch in enumerate(line):
            if ch != ".":
                rows[oy + j][ox + i] = ch
    return tuple("".join(r) for r in rows)


BUBBLE_CODES = {"A": ("ink", 3), "B": ("white", 2), "k": ("ink", 1), "c": ("cinnabar", 2), "g": ("gold", 2),
                "j": ("jade", 2), "Z": ("gold", 3)}

BUBBLES = [
    Obj("bubble.exclaim", "「！」气泡", 16, 16, (_bubble([
        "...cc....",
        "...cc....",
        "...cc....",
        "...cc....",
        ".........",
        "...cc....",
    ], 2, 2),), BUBBLE_CODES, note="惊叹：有事发生 / 被发现。"),
    Obj("bubble.ellipsis", "「…」气泡", 16, 16, (_bubble([
        ".........",
        ".........",
        ".........",
        ".k..k..k.",
        ".........",
    ], 2, 2),), BUBBLE_CODES, note="沉默 / 思考。"),
    Obj("bubble.path", "路径行动气泡", 16, 16, (_bubble([
        "...gg....",
        "..g..g...",
        ".g.ZZ.g..",
        "..g..g...",
        "...gg....",
        ".........",
    ], 2, 2),), BUBBLE_CODES, note="通用：这个人有路径行动可用（金色菱环）。"),
    Obj("bubble.path_inquire", "打探气泡", 16, 16, (_bubble([
        "..kkk....",
        ".k...k...",
        ".....k...",
        "...kk....",
        "...k.....",
        "...k.....",
    ], 2, 1),), BUBBLE_CODES, note="路径行动·打探（问号）。"),
    Obj("bubble.path_buy", "求购气泡", 16, 16, (_bubble([
        "..ZZZZZ..",
        ".Zg...gZ.",
        ".Z.gZg.Z.",
        ".Zg...gZ.",
        "..ZZZZZ..",
        ".........",
    ], 2, 2),), BUBBLE_CODES, note="路径行动·求购（铜钱）。"),
    Obj("bubble.path_duel", "切磋气泡", 16, 16, (_bubble([
        "k.....k..",
        ".k...k...",
        "..k.k....",
        "...k.....",
        "..c.c....",
        ".c...c...",
    ], 2, 1),), BUBBLE_CODES, note="路径行动·切磋（交叉的两把剑）。"),
]

OBJECTS: tuple[Obj, ...] = (ALCHEMY, FORGE, TALISMAN, FORMATION, FIELD, MEDITATE, SHOP, BOARD, SAVE,
                            *ARROWS, DOORLIGHT, SPARKLE, *BUBBLES)


GLOW_ALPHA = {3: 255, 2: 200, 1: 136, 0: 72}


def render_obj_frame(obj: Obj, rows: tuple[str, ...]) -> tuple[Image.Image, Image.Image]:
    """返回 (彩色帧, 发光层帧)。

    不描边的物件（传送箭头、闪光）是纯光，运行时加色画：按明暗级给 alpha，
    暗一级就淡一级——不然整片实心的光在加色下是一块亮斑，不是光。
    """
    if obj.id in PROCEDURAL:
        img = PROCEDURAL[obj.id](rows)
        return img, img
    c = Canvas(obj.w, obj.h)
    c.stamp(list(rows), 0, 0, obj.codes)
    if obj.outline:
        c = add_outline(c, MATS)
    img = to_image(c, MATS)
    if not obj.outline:
        gpx = img.load()
        for y in range(c.h):
            for x in range(c.w):
                v = c.px[y][x]
                if v is not None:
                    r, g, b, _ = gpx[x, y]
                    gpx[x, y] = (r, g, b, GLOW_ALPHA.get(v[1], 255))
    # 发光层：只留发光材质的像素
    em = Canvas(obj.w, obj.h)
    for y in range(c.h):
        for x in range(c.w):
            v = c.px[y][x]
            if v is not None and v[0] in EMISSIVE and v[1] >= 0:
                em.px[y][x] = v
    return img, to_image(em, MATS)


def _anchor(img: Image.Image) -> tuple[int, int]:
    """落地点：最低一行不透明像素的下沿（y），与那一行像素的中点（x）。

    从图里算而不是手填：手填的锚点改一次模板就可能差一行，物件就悬空或陷进地里。
    对头顶气泡，最低一行是气泡的尾尖，所以 x 自然落在尾尖上。
    """
    a = img.getchannel("A")
    w, h = img.size
    for y in range(h - 1, -1, -1):
        xs = [x for x in range(w) if a.getpixel((x, y)) > 0]
        if xs:
            # 纯整数：round() 是四舍六入五成双，奇数宽的那一行会偏一格
            return ((xs[0] + xs[-1] + 1) // 2, y + 1)
    return (w // 2, h)


def pack_objects(sheet_w: int = 256) -> tuple[Image.Image, Image.Image, dict]:
    """把全部物件按「货架」装进一张图。每件的帧横排；放不下就换行。"""
    for obj in OBJECTS:
        # 以 16px 为一格：帧宽高都得是格的整数倍，图集里的位置也就自然对齐到格
        assert obj.w % CELL == 0 and obj.h % CELL == 0, f"{obj.id} 帧尺寸 {obj.w}×{obj.h} 不是 {CELL} 的倍数"
    placements: list[tuple[Obj, int, int]] = []   # (obj, x, y) 第 0 帧位置
    x = y = shelf_h = 0
    for obj in OBJECTS:
        total_w = obj.w * len(obj.frames)
        if x + total_w > sheet_w:
            x = 0
            y += shelf_h
            shelf_h = 0
        placements.append((obj, x, y))
        x += total_w
        shelf_h = max(shelf_h, obj.h)
    height = y + shelf_h
    height = ((height + CELL - 1) // CELL) * CELL
    sheet = Image.new("RGBA", (sheet_w, height), (0, 0, 0, 0))
    emis = Image.new("RGBA", (sheet_w, height), (0, 0, 0, 0))
    index: dict[str, dict] = {}
    for obj, ox, oy in placements:
        rects = []
        first_img = None
        for i, rows in enumerate(obj.frames):
            img, em = render_obj_frame(obj, rows)
            if first_img is None:
                first_img = img
            fx = ox + i * obj.w
            sheet.paste(img, (fx, oy))
            emis.paste(em, (fx, oy))
            rects.append([fx, oy, obj.w, obj.h])
        index[obj.id] = {
            "name": obj.name, "frames": rects,
            "anchor": [obj.w // 2, obj.h] if obj.ground_marker else list(_anchor(first_img)),
            "fps": obj.fps, "note": obj.note,
            "blend": "add" if not obj.outline else "alpha",
        }
    return sheet, emis, index
