-- @hook ch10_tiandujie trigger_baishuilou interact once
talk("", "ch10.baishuilou.signs")
talk("", "ch10.baishuilou.names")
talk("cao_lu", "ch10.baishuilou.cao")
talk("qu_hun_huashen", "ch10.baishuilou.qu")
talk("", "ch10.baishuilou.ouyang")
talk("", "ch10.baishuilou.box")
talk("ouyang_daoyou", "ch10.baishuilou.gift")
talk("cao_lu", "ch10.baishuilou.task")
talk("cao_lu", "ch10.baishuilou.elders")
talk("", "ch10.baishuilou.think")
talk("qu_hun_huashen", "ch10.baishuilou.wait")
give("material_xuelingshui", 2)
give("material_tianhuoye", 2)
talk("", "ch10.baishuilou.keep")
flag.set("ch10.liulian")
