-- @hook ch10_kuixing trigger_dengxian interact once
advance_days(3)
talk("", "ch10.dengxian.news")
talk("", "ch10.dengxian.route")
talk("", "ch10.dengxian.meet")
talk("wen_qiang", "ch10.dengxian.guard")
talk("wen_qiang", "ch10.dengxian.skill")
talk("hanli", "ch10.dengxian.ask")
talk("wen_qiang", "ch10.dengxian.peaks")
talk("wen_qiang", "ch10.dengxian.best")
talk("wen_qiang", "ch10.dengxian.lord")
talk("wen_qiang", "ch10.dengxian.deputy")
talk("", "ch10.dengxian.surprise")
talk("", "ch10.dengxian.outside")
flag.set("ch10.dengxian")
teleport("ch10_kuixing", 14, 20)
