-- @hook ch10_xiaohuan trigger_lifu interact once
local ok, code = realm.cap(realm.QI_REFINING_9)
if not ok then talk("", "ch10.error.realm"); return end
field.unlock("field_xiaohuan", 4)
give("herb_zishen_cao", 2, 1)
give("herb_xuehong_zhi", 2, 1)
talk("", "ch10.lifu.field")
talk("", "ch10.lifu.bottle")
talk("", "ch10.lifu.rooms")
talk("", "ch10.lifu.risk")
talk("", "ch10.lifu.body")
talk("", "ch10.lifu.puppet")
talk("", "ch10.lifu.order")
talk("", "ch10.lifu.pill")
talk("", "ch10.lifu.low")
talk("", "ch10.lifu.old")
talk("", "ch10.lifu.three")
advance_days(1)
flag.set("ch10.kaifu_ri", today())
flag.set("ch10.dingce")
