-- @hook ch10_haichuan trigger_yetan interact once
talk("hanli", "ch10.yetan.ask")
talk("wang_changqing", "ch10.yetan.work")
talk("hanli", "ch10.yetan.ask_isolation")
talk("wang_changqing", "ch10.yetan.mist")
talk("hanli", "ch10.yetan.ask_weather")
talk("wang_changqing", "ch10.yetan.wind")
talk("hanli", "ch10.yetan.ask_beasts")
talk("wang_changqing", "ch10.yetan.beast")
talk("", "ch10.yetan.alone")
talk("hanli", "ch10.yetan.why")
talk("wang_changqing", "ch10.yetan.ten")
talk("hanli", "ch10.yetan.ask_gu")
talk("wang_changqing", "ch10.yetan.gu")
talk("hanli", "ch10.yetan.ask_cargo")
talk("wang_changqing", "ch10.yetan.bags")
talk("hanli", "ch10.yetan.no")
talk("wang_changqing", "ch10.yetan.plead")
talk("", "ch10.yetan.refuse")
talk("wang_changqing", "ch10.yetan.offer")
talk("hanli", "ch10.yetan.ask_guarantee")
talk("wang_changqing", "ch10.yetan.guarantee")
talk("hanli", "ch10.yetan.ask_land")
talk("wang_changqing", "ch10.yetan.contest")
talk("", "ch10.yetan.insight")
local pick = choice({"ch10.yetan.opt_ask", "ch10.yetan.opt_yes"})
if not pick then return end
if pick == 1 then talk("hanli", "ch10.yetan.ask_first")
else talk("hanli", "ch10.yetan.yes_first") end
talk("wang_changqing", "ch10.yetan.answer")
talk("", "ch10.yetan.plan")
advance_days(1)
flag.set("ch10.yetan", pick)
