-- @hook ch10_jinhai trigger_zhenmen interact once
talk("", "ch10.zhenmen.setup")
talk("", "ch10.zhenmen.letter")
talk("feng_sanniang", "ch10.zhenmen.thunder")
local won = battle("b10_liuliandian_weisha")
if not won then game_over(); return end
talk("", "ch10.zhenmen.break")
talk("", "ch10.zhenmen.pin")
talk("", "ch10.zhenmen.freeze")
bgm("bgm_night")
talk("", "ch10.zhenmen.wu")
talk("wu_chou", "ch10.zhenmen.gift")
talk("", "ch10.zhenmen.think")
talk("miao_zhanglao", "ch10.zhenmen.life")
talk("wu_chou", "ch10.zhenmen.skill")
talk("", "ch10.zhenmen.cut")
talk("", "ch10.zhenmen.halt")
talk("wu_chou", "ch10.zhenmen.identity")
talk("", "ch10.zhenmen.token")
talk("", "ch10.zhenmen.escape")
bgm("map")
flag.set("ch10.taoli")
teleport("ch10_jinhai", 20, 16)
